### ISSUE TITLE
Config parser hangs when using .ini file

### ISSUE THREAD

**Issue by jakobod** [actor-framework/actor-framework#1116]
I am using the current `master` to build an application, for which I am using the now deprecated `.ini` file for config options.
The application hangs though and won't do anything when an `.ini` file is present. This is the output of lldb:
```
Process 70209 launched: '/Users/boss/code/caf-net-benchmarks/release/pingpong_udp' (x86_64)
Process 70209 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = signal SIGSTOP
    frame #0: 0x00000001001f180c libcaf_core.0.18.0.dylib`void caf::detail::parser::read_config_map<false, caf::parser_state<caf::(anonymous namespace)::config_iter, caf::(anonymous namespace)::config_sentinel>, caf::detail::config_consumer&>(caf::parser_state<caf::(anonymous namespace)::config_iter, caf::(anonymous namespace)::config_sentinel>&, caf::detail::config_consumer&) + 540
libcaf_core.0.18.0.dylib`caf::detail::parser::read_config_map<false, caf::parser_state<caf::(anonymous namespace)::config_iter, caf::(anonymous namespace)::config_sentinel>, caf::detail::config_consumer&>:
->  0x1001f180c <+540>: andl   %ecx, %eax
    0x1001f180e <+542>: testl  %eax, %eax
    0x1001f1810 <+544>: jne    0x1001f1960               ; <+880>
    0x1001f1816 <+550>: cmpb   $0x5f, %r14b
```
After deleting the file everything works as expected.
I understand, that the "deprecated" `.ini` format should still be usable as a fallback. Is that right?

**Comment by Neverlord** [comment]
Can you share the content of the file?

**Comment by jakobod** [comment]
Of course.
```
[scheduler]
max-threads=4
```

**Comment by jakobod** [comment]
Small addition: I am moving to the new `.conf` file now. The problem will also occur, when both file formats are present. After removing the `.ini` file, everything works as expected.

**Comment by Neverlord** [comment]
Thanks! I'm actually thinking whether the downward compatibility is a good idea after all. Since we finally have a config format that nests nicely, I think we should do the obvious thing and don't pollute the global section any longer. So, instead of:

```
scheduler {
  max-threads = 4
  # ...
}
logger {
  console = 'colored'
  # ...
}
```

we could (should?) move everything to a `caf` section:

```
caf {
  scheduler {
    max-threads = 4
    # ...
  }
  logger {
    console = 'colored'
    # ...
  }
}
```

This allows users to define their own `logger` section for example. Also, I think we should overhaul the `logger` section anyways, which would invalidate any `INI`-file users may have floating around regardless of that change. Adding some extra translation layer to keep old `INI`-files compatible seems like a waste of developer time TBH.
