### ISSUE TITLE
use non-encrypt communication when connect using caf::io::remote_actor before caf::openssl::remote_actor

### ISSUE THREAD

**Issue by superxcgm** [actor-framework/actor-framework#1128]
I publish two actors on server side, first using `caf::io::publish` on port `50602`, and second using `caf::openssl::publish` on port `50603`.
When the client connect to first actor (non-SSL) and then connect to second actor (using SSL). I found it will use non-encrypt communication on port `50602` when I try to use `anon_send` to communicate with second actor which publish using SSL. And I can see the data send to second actor in plain text via Wireshark.
Server and client running on different process.
While if client connect to second actor(using SSL) first and then connect to first actor(non-SSL).  The communication became encrypt and using port `50603`.
I'm wondering whether this is a bug?

demo code:
server.cpp
```
#include "caf/all.hpp"
#include "caf/io/all.hpp"
#include "caf/openssl/all.hpp"

using namespace caf;

behavior make_pong_behavior() {
    return {
            [](std::string str) {
                std::cout << "receive msg: " << str << std::endl;
            }
    };
}

behavior make_pong_ssl_behavior() {
    return {
            [](std::string str) {
                std::cout << "ssl receive msg: " << str << std::endl;
            }
    };
}

void caf_main(actor_system &system) {
    caf::expected<uint16_t> expected_port(0);
    auto spong = system.spawn(make_pong_behavior);
    std::cout << "spong id: " << spong.id() << ", address: " << caf::to_string(spong.address()) << std::endl;
    expected_port = caf::io::publish(spong, 50602);
    if (!expected_port) {
        std::cout << "publish spong failed. reason: " << system.render(expected_port.error()) << std::endl;
        exit(1);
    }
    auto spong_ssl = system.spawn(make_pong_ssl_behavior);
    std::cout << "spong_ssl id: " << spong_ssl.id() << ", address: " << caf::to_string(spong_ssl.address()) << std::endl;
    expected_port = caf::openssl::publish(spong_ssl, 50603);
    if (!expected_port) {
        std::cout << "publish spong failed. reason: " << system.render(expected_port.error()) << std::endl;
        exit(1);
    }

    std::cout << "already publish all actor, press [Enter] to exit" << std::endl;

    std::string dummy;
    std::getline(std::cin, dummy);
}

CAF_MAIN(caf::io::middleman, caf::openssl::manager)

```

client.cpp
```
#include "caf/all.hpp"
#include "caf/io/all.hpp"
#include "caf/openssl/all.hpp"
#include <string>
#include <iostream>

using namespace caf;

caf::actor connect_tcp_worker(caf::actor_system &system, const std::string &host) {
    auto result = caf::io::remote_actor(system, host, 50602);
    if (!result) {
        std::cout << "connect failed, reason: " << system.render(result.error()) << std::endl;
        exit(1);
    }
    std::cout << "address: " << caf::to_string(result->address()) << std::endl;
    return *result;
}

caf::actor connect_ssl_worker(caf::actor_system &system, const std::string &host) {
    auto result_ssl = caf::openssl::remote_actor(system, host, 50603);
    if (!result_ssl) {
        std::cout << "ssl connect failed, reason: " << system.render(result_ssl.error()) << std::endl;
        exit(1);
    }
    std::cout << "address: " << caf::to_string(result_ssl->address()) << std::endl;
    return *result_ssl;
}

[[noreturn]] void caf_main(actor_system &system) {
    std::string dummy;
//    std::cout << "Please input remote host: ";
//    std::getline(std::cin, dummy);
//    std::string host = dummy;
    std::string host = "localhost";
    auto spong = connect_tcp_worker(system, host);
    auto spong_ssl = connect_ssl_worker(system, host);

    while (true) {
        std::getline(std::cin, dummy);
        if (dummy == "n") {
            caf::anon_send(spong, "hello");
            continue;
        }
        if (dummy == "s") {
            caf::anon_send(spong_ssl, "hello");
            continue;
        }
    }
}

CAF_MAIN(caf::io::middleman, caf::openssl::manager)

```

**Comment by Neverlord** [comment]
> I'm wondering whether this is a bug?

Not a bug, but the API is a bit misleading and gives a wrong impression how things work underneath. Let me explain.

CAF maintains connections *per node*. The interface suggests that you are making a single actor available at a port and then connect to that actor via `remote_actor`, but you are really connecting two CAF nodes. If you are connecting to a CAF node, the server sends the ID of the actor that was published at that port. So the functions really mix two things: node connections and actor rendezvous.

CAF always maintains only a single connection between two nodes. Any actor-to-actor messaging is going to use that connection. If you are calling `remote_actor` multiple times, you learn new actor IDs from the target node but CAF closes all extra connections immediately after the handshake.

We are aware that this API design is confusing to users. That's why we are already working on a replacement for `caf.io` called `caf.net` in our [incubator](https://github.com/actor-framework/incubator). In the new design, you'll be able to lookup remote actors by user-defined names and CAF nodes only open a single port during setup. Also, you'll no longer have to hardwire the transport with function calls.

To cut a long story short: don't mix `caf.io` and `caf.openssl`. If you need encryption, use the `openssl` module consistently. Once the connections are established, CAF doesn't know whether a connection is encrypted or not and always discards extra connections to nodes it is already connected to.

**Comment by superxcgm** [comment]
I also found that there is no `caf::openssl::connect` and `caf::openssl::open`. So I have to mix `caf.io` and `caf.openssl`. Or I have to remove `connect` and `open` from my app to get an encrypt connection.

**Comment by superxcgm** [comment]
After reading the [document](https://actor-framework.readthedocs.io/en/latest/RemoteSpawn.html#remote-spawn), I find ways no to use `caf::io::connect` and `caf::io::open`. Thanks for you help.
