### ISSUE TITLE
`caf::result` constructor ambiguity

### ISSUE THREAD

**Issue by uentity** [actor-framework/actor-framework#1245]
Here's simple code that trigger compile error in CAF 0.18.2:
```C++
#include <caf/result.hpp>

struct X {
	X(bool) {}
};

auto g() {
	return caf::result<X>{true};
}
```
GCC 11 output:
```
call of overloaded ‘result(<brace-enclosed initializer list>)’ is ambiguous
||    62 |         return caf::result<X>{true};
||       |                                   ^
|| In file included from kernel/src/property.cpp:14:
third_party/actor-framework/libcaf_core/caf/result.hpp|191 col 3| note: candidate: ‘caf::result<T>::result(caf::expected<T>) [with T = blue_sky::prop::X]’
||   191 |   result(expected<T> x) {
||       |   ^~~~~~
third_party/actor-framework/libcaf_core/caf/result.hpp|187 col 3| note: candidate: ‘caf::result<T>::result(T) [with T = blue_sky::prop::X]’
||   187 |   result(T x) : super(detail::result_base_message_init{}, std::move(x)) {
||       |   ^~~~~~
```
Porting my code to CAF 0.18.2 and constantly hitting this error to the point that no easy workaround exists.

**Comment by Neverlord** [comment]
Yeah, implicit conversions are fun... It seems like the compiler can't decide whether to implicitly convert the `bool` to an `X` or an `expected<X>`. The latter accepts any constructor arguments that allow it to construct an `X`, which is why the compiler deems the two conversions equally viable. Probably dropping the template constructor in `expected` and instead having a constructor taking an `X` instead could solve this (because in this case the compiler always has to convert to `X` first and should pick the preferred overload). I'm not sure if there are edge cases where this would be a breaking API change, though.

In the meantime, does it work if you write it like this?

```cpp
auto g() -> caf::result<X> {
  return X{true};
}
```

**Comment by uentity** [comment]
> In the meantime, does it work if you write it like this?
> 
> ```c++
> auto g() -> caf::result<X> {
>   return X{true};
> }
> ```

Yes, this case can be fixed that way. But I have generic code where type `X` is not known (and I cannot 'reconstruct' it from `caf::result<T>`), so it heavily relies on implicit conversions and expects the right constructor overload to be chosen.

In particular, I have transaction evaluator where transaction can return either `R` or `result<R>`, and if error occurs evaluator returns error value that is implicitly convertible to `R`. Inside evaluator I can't obtain type `R` without passing additional context. Also placing `result<T>` inside `std::expected` with delayed initialization can cause problems, etc.

I've proposed a solution #1246 that seems to fix all my code and don't break CAF tests & examples compilation (didn't run 'em though, but at a glance everything seems to be OK). Idea is to always make value-initializing constructor a best possible candidate if value is implicitly convertible to `T`.

**Comment by Neverlord** [comment]
> I've proposed a solution #1246 that seems to fix all my code and don't break CAF tests & examples compilation ...

Thanks a lot for submitting a fix! The patch LGTM and passes CI, so I've just merged it to the main branch. 🎉
