### ISSUE TITLE
Delayed messages and aggressive work-stealing causes high cpu load?

### ISSUE THREAD

**Issue by al3ph** [actor-framework/actor-framework#1251]
Is this expected behaviour ? We're seeing high CPU usage, as far as we can tell it's related to delayed messages and aggressive work stealing.

Does this seem likely ? I've not tried building a testbed, but from the docs, it would imply a delayed message in the worker queues might stop the aggressive work stealing from sleeping ? Hence a constant scanning of the queues.

**Comment by al3ph** [comment]
This might be bogus, as I can't reproduce this effect, (was reported by someone else).

**Comment by al3ph** [comment]
Right can now reproduce the effect, seeing 40% cpu load when stealing enabled vs 2% with it disabled.

**Comment by Neverlord** [comment]
That's probably just an artifact of the work stealing itself. Work stealing is fast, because there is little to no synchronization between worker threads. The downside is, there is little to no synchronization between the workers. 😉

This means there is no central controller that can put idle threads to sleep and wake them up as needed. Instead, workers periodically wake up and check whether they can find (steal) some work. The work stealing implementation in CAF is very straightforward at the moment and uses polling with increasing sleep intervals over time. Polling inherently has some CPU overhead for otherwise idle systems. There are some hybrid approaches (like hierarchical work stealing) that allow some synchronization between workers for reducing spinning, but the implementations are more complex and would require extensive testing to make sure they still perform similar for high loads.

If the system you are working on only has a couple of cores anyway (or you limit the thread pool size for other reasons), you can try whether the work sharing scheduler gives you sufficient performance.

**Comment by al3ph** [comment]
Ah cool I thought that might be the case. Just need to watch out for spurious load from bad code. My machine has 40+ cores. So might be an issue, though we're not throwing around that many messages.

Cheers for the detailed info.
