### ISSUE TITLE
Turn actor_addr into string and then reconstitute?

### ISSUE THREAD

**Issue by al3ph** [actor-framework/actor-framework#1260]
Bit of an odd one this, but is it possible to turn an actor_addr into a string then recreate it from the string ?

Basically I need to turn the actor_addr into a URL, then back again, this is due to the way I need to build icons in QML, the source for the icon needs to be a URL.

This is all happening inside the same process, so the icon builder has access to the actor system, it's just it's only input has to be a URL.

Also is this the right place to be asking for help ? Or should I use glitter or something?

cheers

**Comment by al3ph** [comment]
Doing to_string(actor_addr) produces something that looks suspiciously like a serialise buffer that is  hex encoded ?

**Comment by Neverlord** [comment]
> This is all happening inside the same process, so the icon builder has access to the actor system, it's just it's only input has to be a URL.

The answer depends a bit on what actors you're working with. Is the icon builder only seeing locally running actors? Then you could use the registry. Calling `put(handle.id(), handle)` associates an actor with its ID and `get<actor>(id)` gives you the handle back. So if you're only exposing local actors, an URI like `foobar:123` would be enough (and then you generate the integer from the actor ID).

If you're also allowing access to remote actors, then you need to roll some custom mapping since you also need the node ID. To address an actor in the distributed system, CAF uses a node ID (selects a single actor system) plus an actor ID (selects a single actor from the system). The latter is just an integer. The former depends on the loaded modules. When loading the `caf_io` module, a node ID is a unique ID (essentially random bytes) plus the process ID. With the I/O module, the `to_string` output gives you `<actor-id>@<node>#<pid>`. For turning this into an URI, you probably need to split up the work. First call `to_string` only on the node ID and pass it to an URI encoder (otherwise `#` selects the fragment). Then you can have an URI like `foobar:<node-id>/<actor-id>`.

To get the node ID back, there's a [parse](https://github.com/actor-framework/actor-framework/blob/master/libcaf_core/caf/node_id.hpp#L286) function available. The actor ID is just an integer, so should be easy to deal with. The registry won't help you with those URIs, though. So you'll also have to have a `map` somewhere that translates a node ID + actor ID pair back to actor handles.

> Also is this the right place to be asking for help ? Or should I use glitter or something?

We don't have a "preferred" forum quite yet. I'd say either here or on the mailing list. Gitter is best for really short questions.

**Comment by al3ph** [comment]
Could you just binary_serialise the actor_addr then hex encode the buffer, then reverse at the other end ?

**Comment by Neverlord** [comment]
> Could you just binary_serialise the actor_addr then hex encode the buffer, then reverse at the other end ?

Depends. Under the hood, these will call `load_actor` and `save_actor`. As long as you're only dealing with local actor addresses, they'll go through the registry like I've mentioned. This would work as long as you don't mind the rather cryptic URIs that come out of this.

For remote actors, however, this function pair requires you to configure a proxy registry or else you'll see `sec::no_proxy_registry` errors. Implementing a custom proxy registry probably isn't worth the troubles here TBH.

**Comment by al3ph** [comment]
I was trying to avoid putting every target actor into the registry, their maybe hundreds of them. I assumed the serialise/deserialise would avoid that, as it'd just work the same as passing the actor_addr via a message.
