### ISSUE TITLE
Fail to send mass data

### ISSUE THREAD

**Issue by ChenKang256** [actor-framework/actor-framework#1350]
I have 400 actors on the remote server, and each actor will send 15MB data to the corresponding local actor at the same time. However, I fail to send these 6GB data using `anon_send`. Is there any limitation for total message size when sending them at the same time?

**Comment by Neverlord** [comment]
The only hard limit in CAF is that messages use a 32-bit size field on the wire and thus may not exceed ~2GB. But since your individual messages are smaller, they should arrive eventually. Without any code it's hard to tell whether there's an issue in CAF or in some other component. Can you provide a small, standalone program that reproduces the behavior?

**Comment by ChenKang256** [comment]
I wrote a simple program based on the sample program

**Comment by ChenKang256** [comment]
I write a simple program based on the sample program.
```c++
// This program illustrates how to spawn a simple calculator
// across the network.
//
// Run server at port 4242:
// - remote_spawn -s -p 4242
//
// Run client at the same host:
// - remote_spawn -H localhost -p 4242

#include <array>
#include <cassert>
#include <functional>
#include <iostream>
#include <sstream>
#include <string>
#include <vector>
#include <fstream>

#include "caf/all.hpp"
#include "caf/io/all.hpp"

// --(rst-calculator-begin)--
using calculator
  = caf::typed_actor<caf::result<void>(std::string)>;
// --(rst-calculator-end)--

CAF_BEGIN_TYPE_ID_BLOCK(remote_spawn, first_custom_type_id)

  CAF_ADD_TYPE_ID(remote_spawn, (calculator))

CAF_END_TYPE_ID_BLOCK(remote_spawn)

using std::cerr;
using std::cout;
using std::endl;
using std::string;

using namespace caf;

calculator::behavior_type calculator_fun(calculator::pointer self) {
  return {
    [=](std::string msg) {
      aout(self) << "Received messages from a remote node." << endl;
      // aout(self) << "The content is: " + msg[0] << endl;
    },
  };
}

struct config : actor_system_config {
  config() {
    add_actor_type("calculator", calculator_fun);
    opt_group{custom_options_, "global"}
      .add(port, "port,p", "set port")
      .add(host, "host,H", "set node (ignored in server mode)")
      .add(server_mode, "server-mode,s", "enable server mode");
  }
  uint16_t port = 0;
  string host = "localhost";
  bool server_mode = false;
};

void server(actor_system& system, const config& cfg) {
  auto res = system.middleman().open(cfg.port);
  if (!res) {
    cerr << "*** cannot open port: " << to_string(res.error()) << endl;
    return;
  }
  cout << "*** running on port: " << *res << endl
       << "*** press <enter> to shutdown server" << endl;
  getchar();
}

// --(rst-client-begin)--
void client(actor_system& system, const config& cfg) {
  auto node = system.middleman().connect("192.168.1.5", cfg.port);
  if (!node) {
    cerr << "*** connect failed: " << to_string(node.error()) << endl;
    return;
  }
  auto type = "calculator";             // type of the actor we wish to spawn
  auto args = make_message();           // arguments to construct the actor
  auto tout = std::chrono::seconds(30); // wait no longer than 30s
  auto worker_num = 1500;               // the number of actors we want
  std::vector<typed_actor<caf::result<void>(std::string)>> workers; 
  for (int i = 0; i < worker_num; i++) {
    workers.push_back(*system.middleman().remote_spawn<calculator>(*node, type, args,
                                                            tout));
  }
  // start using worker in main loop
  std::ifstream ifs("..."); //A 15MB file
  std::string msg(
                  (std::istreambuf_iterator<char>(ifs)),
					        (std::istreambuf_iterator<char>()) 
                  );
  ifs.close();
  cout << "Single message size: " + std::to_string(msg.length() * sizeof(char)) + " Bytes"<< endl;
  for (int i = 0; i < worker_num; i++) {
    anon_send(workers[i], msg);
  }
  cout << "Successful send " + std::to_string(worker_num) + " messages" << endl;
  for (int i = 0; i < worker_num; i++) {
    // anon_send_exit(workers[i], exit_reason::kill);
  }
}
// --(rst-client-end)--

void caf_main(actor_system& system, const config& cfg) {
  auto f = cfg.server_mode ? server : client;
  f(system, cfg);
}

CAF_MAIN(id_block::remote_spawn, io::middleman)

```
Here I fail to receive any message in remote server when I have spawned 1500 actors. Also, I fail to send a 4GB message when there's only one actor spawned in remote server. Is there any problem in my code? Or have I misunstood anything?

**Comment by riemass** [comment]
Hi @ChenKang256. I've tested the provided program on my machine (notebook - Intel i5 8. gen with 16GB of RAM). I couldn't quite reproduce the result, and I'm using the current head branch of CAF, so an eventual bug was either fixed since reporting the bug, or you simply run out of memory, since I've noted quite a spike when running the example above. 
Here are some limits I've tested that do work:

- 16MB to 100 actors, 
- 1.4 MB payload to 3000 actors,
- 0.5MB payload to 10000 actors.

When experimenting with different sizes, I would quite often run out of memory which would kill the client process. Analyzing example, all data is first stored in main memory, and upon every `anon_send` we copy the data for every spawned worker. Including the memory overhead of dynamic data structure, this memory spike seems normal to me. I would suggest processing big files in chops, and using some kind of copy on write mechanism, in this case you can look at `caf::cow_string` or even `caf::message` to get  
Those are the limits on my machine

**Comment by riemass** [comment]
Hi @ChenKang256. I've tested the provided program on my machine (notebook - Intel i5 8. gen with 16GB of RAM). I couldn't quite reproduce the result, and I'm using the current head branch of CAF, so an eventual bug was either fixed since reporting the bug, or you simply run out of memory, since I've noted quite a spike when running the example above. 
Here are some limits I've tested that do work:

- 2GB to 2 actors, 
- 16MB to 100 actors, 
- 1.4 MB payload to 3000 actors,
- 0.5MB payload to 10000 actors.

When experimenting with different sizes, I would quite often run out of memory which would kill the client process. This happens whenever I increase the number of worker or the payload size more than the above limits. Analyzing the example, all data is first stored in main memory, then copied for every spawned worker when using `anon_send` and then stored in the server process for every spawned worker. Including the memory overhead of dynamic data structures and the framework, this memory spike seems expected.
I would suggest processing big files in chops, and using some kind of copy on write mechanism, in this case storing the message as `caf::cow_string` or `caf::message` would help.
