### ISSUE TITLE
std::bad_alloc in basp_broker 

### ISSUE THREAD

**Issue by thunderZH963** [actor-framework/actor-framework#1351]
While running performance tests involving several nodes, we eventually get an unhandled exception in basp_broker:

*** unhandled exception: ... : std::bad_alloc

The buffer in which message sent to other nodes are serialized goes too large.(It will exceed our system memory limit)

Are there any solutions and suggestions?

Looking forward to your reply.

**Comment by Neverlord** [comment]
If you see a `bad_alloc`, it means your system is out of RAM. At that point, there's really nothing CAF could do.

In general, the messaging system is asynchronous. Pushing data into the system nonstop without adding any feedback mechanism will blow up your application. Flows/streams are better suited for transferring large chunks of data since they implement backpressure (fast senders cannot overwhelm slow receivers), but the new streams for 0.19 are not quite ready yet. So if you can't wait for them, at least the application should have some form of signaling to provide feedback to your senders.
