### ISSUE TITLE
Update OS versions in the pipeline and bring back Jenkins

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#1420]
- [x] Replace EOL Linux distributions with newer versions
- [x] Add FreeBSD 13 to the mix
- [x] Get back Jenkins and use it for the Linux workers

**Comment by riemass** [comment]
Almalinux 8 still maintained reaching EOL 01 Mar 2029, but there is also Almalinux 9 reaching EOL 31 May 2032.
Also, CentOS 7 is still supported until 30 Jun 2024, with CentOS 9 being maintained and shifting to a roling release distribution. 

@Neverlord should I add Almalinux 9 and CentOS 9 Stream to the mix?

We can update:
- Fedora 35 -> 37 
- Fedora 36 -> 38

Since currently only 36 is being run by cirrus, I believe we should also only run 38 and delete 37/36.

**Comment by Neverlord** [comment]
> @Neverlord should I add Almalinux 9 and CentOS 9 Stream to the mix?

Yes, but only after we switch the Linux builds back to our Jenkins. We have limited "credit" on Cirrus but not on our Jenkins. Let me resurrect our Jenkins setup this week. I'll make a PR to switch the Linux images over.

The plan is to have Windows, FreeBSD and macOS on Cirrus (because we don't want to maintain these ourselves) and all of the Linux versions over on Jenkins (they basically require no maintenance since we can launch them from Dockerfiles).

> We can update:
>
> - Fedora 35 -> 37
> - Fedora 36 -> 38

Yep, go ahead with those. 👍

You can also add FreeBSD 13 as a followup (plus macOS). Is FreeBSD 12 still supported? Otherwise it should get removed/replaced as well.

**Comment by riemass** [comment]
FreeBSD is supported until end of this year (31.Dec.2023). We could have both until then.

**Comment by Neverlord** [comment]
> @Neverlord should I add Almalinux 9 and CentOS 9 Stream to the mix?

@riemass on second thought, I think CentOS 9 Stream probably won't add much. It's a rolling release, isn't it? But I think Alpine would be a good idea since it's using a different C standard library. So I'd say AlmaLinux 9 + Alpine after #1431 lands and that should wrap up this ticket.
