### ISSUE TITLE
Add datagram/UDP abstraction for brokers

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#145]
The broker is currently limited to TCP-like backends. A new datagram backend for connectionless networking would significantly broaden its usefulness.

**Comment by kirillv** [comment]
Hi.

Is there any progress on this ticket? Thanks in advance.

**Comment by josephnoir** [comment]
Hello @kirillv. There is no progress, yet. However, it is part of my current work. It will still take a few months as it is part of a larger effort. I'll update the issue when I get to the implementation!

**Comment by kirillv** [comment]
@josephnoir I hope so. I am limited with udp. Thanks in advance.

**Comment by kirillv** [comment]
Hi @josephnoir. Is it possible to see UDP support in 0.15 final release? Thanks in advance.

**Comment by josephnoir** [comment]
Hello @kirillv, I am sorry to say that UDP support won't be included in 0.15. My goal is to be done in September / October.

**Comment by grahamreeds** [comment]
Hi, what is the state of this now that it is September/October?

The udp branch is very stale.

**Comment by josephnoir** [comment]
The branch [topic/network](https://github.com/actor-framework/actor-framework/tree/topic/network) will track my work. Much has changed since the UDP branch was created and I think it is better to start from the develop branch in its current state. I just started on the implementation, but haven't pushed anything yet. Here is a rough outline: 

- [ ] Introduce URIs to replace host and port arguments
  - [ ]  Introduce an URI parser
  - [ ]  Adjust API
- [ ] Implement "datagram-scribes" for the multiplexer (need a better name for those)
- [ ] Enable brokers to adjust protocol guarantees
  - [ ]  Ordering
  - [ ]  Slicing
  - [ ]  Reliability (requires update to send functions)
- [ ] Implement protocol policies to augment raw sockets
- [ ] Proof of concept policy (e.g., HTTP tunneling over a TCP raw socket)

**Comment by Ulimo** [comment]
@josephnoir Hi, I just wanted to check if you plan to implement UDP in its raw form (unreliable).
It would be great if it would be possible to implement layers on top of UDP, such as LEDBAT (https://en.wikipedia.org/wiki/LEDBAT).

**Comment by josephnoir** [comment]
Hello @Ulimo, datagrams will be ordered by the runtime environment per default. Reliability, on the other hand, is planned as an optional guarantee. 

The protocol policies mentioned above should allow implementation of protocols on top of a raw transport protocol (TCP or UDP). Policies are processed before brokers augment any protocol guarantees, i.e., datagrams are delivered unreliably and out of order at this point. My guess is that LEDBAT could be implemented as such a policy.

**Comment by grahamreeds** [comment]
Hi.  Thought I would give the current udp a quick tryout and in it's current checked in form the branch fails to compile (the main branch compiles fine though).

The error is:

> [ 46%] Building CXX object libcaf_io/CMakeFiles/libcaf_io_shared.dir/src/basp_broker.cpp.o
In file included from /home/master/splint/caf/libcaf_io/caf/io/basp/all.hpp:25:0,
                 from /home/master/splint/caf/libcaf_io/caf/io/basp_broker.hpp:37,
                 from /home/master/splint/caf/libcaf_io/src/basp_broker.cpp:20:
/home/master/splint/caf/libcaf_io/caf/io/basp/instance.hpp:144:36: error: ‘new_endpoint_msg’ has not been declared
   bool handle(execution_unit* ctx, new_endpoint_msg& em, endpoint_context& ep);
                                    ^
/home/master/splint/caf/libcaf_io/caf/io/basp/instance.hpp: In constructor ‘caf::io::basp::instance::sequence_number_visitor::sequence_number_visitor(caf::io::basp::instance::callee&)’:
/home/master/splint/caf/libcaf_io/caf/io/basp/instance.hpp:415:57: error: invalid initialization of non-const reference of type ‘caf::io::basp::instance::callee&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     sequence_number_visitor(instance::callee& c) : cal{c} { }
                                                         ^
make[3]: *** [libcaf_io/CMakeFiles/libcaf_io_shared.dir/src/basp_broker.cpp.o] Error 1

Any chance of a quick fix?

**Comment by josephnoir** [comment]
The last commit broke a lot as I started to generalize the UDP implementation. It currently uses a different port for sending and receiving, which is not expected by general applications. 

Using the previous commit should work (3c85ec40). However, there a still a few issues:
* Neither message slicing not reassembly (and thus a size limit for messages sent via UDP)
* No retransmits
* Answers sent from a different port

**Comment by grahamreeds** [comment]
Unfortunately that commit also has errors in it. :-(

> [ 45%] Building CXX object libcaf_io/CMakeFiles/libcaf_io_shared.dir/src/basp_broker.cpp.o
In file included from /home/master/splint/caf/libcaf_io/caf/io/basp/all.hpp:25:0,
                 from /home/master/splint/caf/libcaf_io/caf/io/basp_broker.hpp:37,
                 from /home/master/splint/caf/libcaf_io/src/basp_broker.cpp:20:
/home/master/splint/caf/libcaf_io/caf/io/basp/instance.hpp: In constructor ‘caf::io::basp::instance::sequence_number_visitor::sequence_number_visitor(caf::io::basp::instance::callee&)’:
/home/master/splint/caf/libcaf_io/caf/io/basp/instance.hpp:415:57: error: invalid initialization of non-const reference of type ‘caf::io::basp::instance::callee&’ from an rvalue of type ‘<brace-enclosed initializer list>’
     sequence_number_visitor(instance::callee& c) : cal{c} { }
                                                         ^
make[3]: *** [libcaf_io/CMakeFiles/libcaf_io_shared.dir/src/basp_broker.cpp.o] Error 1

I guess I will have to forgo a quick test of the udp.

**Comment by josephnoir** [comment]
Sorry for that. I mostly develop on macOS with clang. For future reference, what platform and compiler are you using?

**Comment by grahamreeds** [comment]
Ubuntu 14_04 LTS w/ gcc 4.8.4.

Sent from my Nexus 6P

On 19 Mar 2017 7:28 pm, "Joseph Noir" <notifications@github.com> wrote:

Sorry for that. I mostly develop on macOS with clang. For future reference,
what platform and compiler are you using?

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/actor-framework/actor-framework/issues/145#issuecomment-287618467>,
or mute the thread

**Comment by grahamreeds** [comment]
Err, there are two "active" branches for UDP now? topic/udp and topic/network.

[topic/udp was dropped](https://github.com/actor-framework/actor-framework/issues/145#issuecomment-252851544) due to the staleness of that branch and new work was done topic/network.  That reached a certain point but was unusable due to broken checkins and nothing happened for 5 months.

Udp was rebased from develop and now it is active again.  Surely there is someway of not invalidating all the work that has gone into the previous work?

(note: I had thought about creating a new ticket but is related to this older ticket).

**Comment by josephnoir** [comment]
Hi @grahamreeds.

The network branch does not only implement UDP (with responses from the wrong socket), but provides URIs and strips aways routing. I moved to the UDP branch (again) to focus solely on UDP which will hopefully let me progress a bit faster.

I don't think that I am invalidating the work as I can take many changes from the network branch. In the meantime, a few things changed in the related classes and I think it is easier to do this step by step instead of rebasing all the changes on the develop branch at once.

**Comment by Neverlord** [comment]
Implemented with https://github.com/actor-framework/actor-framework/pull/626
