### ISSUE TITLE
Possible bug/issue with flow_bridge_base::prepare_send()

### ISSUE THREAD

**Issue by weberdaniel** [actor-framework/actor-framework#1923]
During experiments with flow_bridge_base in conjunction with a connectionless udp_datagram_socket,  the switch statement in `flow_bridge_base::prepare_send()`  which calls `in_.pull(async::delay_errors,tmp)` always immediately resulted in `async::read_result::abort` resulting in a problem if down_ was not set up already. This is probably because the acceptor logic of tcp/ip does not exist for udp/ip in the first place and prepare_send() got called earlier than in the tcp/ip case using an acceptor. Adding an if statement `if(in_.has_data())` prior to the switch statement in flow_bridge_base::prepare_send() fixed the problem, but this if statement also required to add an else clause with a `return;` statement to not run into an endless loop.

**Comment by Neverlord** [comment]
Just to be sure: you do realize it's an internal class, right? Internal means it is not intended to be used outside of CAF's own `.cpp` files and we won't even install the headers for it.

> immediately resulted in `async::read_result::abort` resulting in a problem if down_ was not set up already

I can't follow along. If `down_` isn't initialized properly (what do you mean by that, that it is `nullptr`?), it should crash/fail right at the beginning, because `prepare_send` starts with `while (down_->can_send_more())`.

In any case, something is very weird in your setup. If no data is available, the switch statement will use its default case for `read_result::try_again_later` and the function will simply `return`. Calling `has_data` prior only masks other issues.

The more interesting question to me is: why did you go down that particular rabbit hole to begin with and what are you trying to do? 🙂

**Comment by weberdaniel** [comment]
That's true, the class feels very internal, but i forgot to mention that i am on 0.19.3.  I consider to refactor a UDP/TCP protocol converter, i thought it might be a good size to serve as an example showcase of using CAF. 

The TCP part works smoothly. For UDP  i started to dig. I adopted lp::client_factory to use make_udp_datagram_socket() instead of detail::tcp_try_connect(). Then, above mentioned prepare_send() started to crash. I fixed it by adding the ` if(in_.has_data()) { SWITCH-STATEMENT } else { return; }`, otherwise  the abort case resulted in down_-> to segfault.  
In the meanwhile i also realized that  the receive buffer needs to be adopted for UDP since UDP datagrams are discarded entirely by the POSIX API when only reading the first 4 octets. That being said the number of possible showstoppers slowly goes to zero.

It's true, probably you cannot follow this item along without knowing the code, but sometimes people just immediatly spot the problem.

**Comment by Neverlord** [comment]
> That's true, the class feels very internal, but i forgot to mention that i am on 0.19.3.

Even in 0.19.3, this wasn't part of the public API since it lived in `caf::detail`. 🙂

The flow bridge wasn't implemented with a datagram-oriented transport in mind. While it allows plugging in a lower layer via template parameter, it has been designed for stream-oriented transports.  We would need re-evaluate the assumptions made by the flow bridge if we were to support flows for datagram-based transports. It's not on our roadmap at the moment, though.

Just from the your report, I can't tell immediately what would need to be done. We would need to dig into it ourselves. Closing, since the ticket really isn't about using a CAF feature, but customizing CAF.
