### ISSUE TITLE
print.hpp: Control characters not escaped correctly

### ISSUE THREAD

**Issue by Masrepus** [actor-framework/actor-framework#1937]
When the `caf::json_writer` serializes a string to json that contains bytes between 0x00 and 0x1f, the resulting json can't be deserialized correctly by e.g. nlohmann::json. The reason for this is that the `print_escaped_to` function in `print.hpp` does not have a special case for these control characters, which should be escaped to `\uxxxx`. An equivalent from nlohmann would be this piece of code: https://github.com/nlohmann/json/blob/ec7a1d834773f9fee90d8ae908a0c9933c5646fc/src/json.hpp#L4678-L4685

**Comment by Neverlord** [comment]
Thanks for reporting!

**Comment by Masrepus** [comment]
Btw, while toying around with a little hotfix locally right now, I realized that the range needs to be even bigger: Any byte above 0x7f needs to be escaped as well, although one thing that I should note that already bit me is that of course since that function deals with a *signed* char, stuff "above" 0x7f is in fact negative...
So probably the easiest fix would be to check whether the value is between 0x00 and 0x1f and the rest just gets escaped

**Comment by Masrepus** [comment]
Hmm I see. In my case, the string I was persisting for whatever reason had non-UTF8 bytes in it, which brings up the question whose concern it should be to make sure the string that is persisted adheres to UTF8: Technically, if a CAF message has an `std::string`, that doesn't necessarily mean it's supposed to be a fully compliant UTF8 string as per the C++ standard. The moment we serialize it however, this of course becomes a problem with the JSON definition of a string, so I would maybe lean towards the opinion that CAF's serializer needs to take care of these strings. One issue that could of course happen is that if you just escape each single byte over `0x80`, you may accidentally break up multi-byte characters. Not sure what the optimal solution to this is, is there maybe a way for the user to express their intent of "this is just a raw `std::string`, no guarantees about its content" vs "this is a compliant UTF8 string, only escape control characters" when defining a message inspector?

**Comment by riemass** [comment]
Using `std::string` for binary data isn't very wise. Nothing in the language forces you to comply, but you have to know what you're doing. For example, try putting a zero byte in the middle of a `std::string` and calling `printf(s.c_str())`.

The rule of thumb in CAF is to use `std::string` for textual data, and `byte_buffer` for binary data, with the latter being an alias for `std::vector<std::byte>`. In this case `json_writer` will serialize a `byte_buffer` as an escaped hex sequence. It has a bigger memory overhead, but it will work out of the box and probably cover your case. I think this answers your last question. 

Part of the problem is also that JSON is a human readable format, and it doesn't support binary data natively. If you're not depending on JSON too much, I could suggest you look at `caf::binary_serializer` for a custom serialization format. It will be more memory efficient but it will require all your data readers to depend on CAF for de-serialization.

**Comment by Neverlord** [comment]
Wise or not, JSON actually *requires* encoding non-printable characters in this way (https://www.ietf.org/rfc/rfc4627.txt):

> All Unicode characters may be placed within the quotation marks except for the characters that must be escaped: quotation mark, reverse solidus, and the control characters (U+0000 through U+001F).

So to be compliant, we need to encode this character set.

**Comment by Masrepus** [comment]
Thinking some more about it, I agree that when working with arbitrary string contents, using a `std::vector<std::byte>` might be the better choice. So yeah, as long as control characters are escaped, the CAF printer fully adheres to the spec and doesn't need to care about any of the bytes that may not be valid UTF8
