### ISSUE TITLE
Add Support for Versioning of Serialized Data

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#246]
CAF's serialization framework currently does not allow developers to store/load data in a backward compatible way. Adding versioning support would address this topic.

**Comment by mavam** [comment]
Here, API compatibility to Boost Serialization might be worth noting. Their customization point comes in the form of free functions `serialize` and `deserialize` in the namespace associated with a serializable type:

```cpp
namespace ns {

struct foo {
  int i;
  int j; // since version 2
};

template <class Archive>
void serialize(Archive& a, const foo& f, unsigned int version) {
  if (version == 2) {
     a(f.j);
  }
  // Serialize rest
  a(f.i);
}

} // namespace ns
``` 

Ideally we'll use an interface similar to [N3980](http://isocpp.org/files/papers/n3980.html) to decouple the state exposure from clients with the serialization library. Then we could later on re-use the same state exposure functions for hashing and other concepts.

**Comment by allspark** [comment]
Maybe we could use https://uscilab.github.io/cereal/ for serialization.

It supports a similar style
```
struct foo {
  int i;
  int j; // since version 2

  template <class Archive>
  void serialize(Archive& a) {
    if (version == 2) {
      a(j);
    }
    // Serialize rest
    a(i);
  }
};
```

or dedicated load/save methods

**Comment by Neverlord** [comment]
@allspark thank you for the link, but CAF already supports a similar syntax (following the boost.serialization API) in the `develop` branch. It "only" needs to be integrated into `announce`, preferably in a downward compatible way.

**Comment by Neverlord** [comment]
Thinking a bit more about this topic: Is there really a scenario where this is feasible in a distributed system? If A sends a message to B and the version differs, the communication is immediately broken if A has a newer version than B. In the provided examples simply because B will try to read `i` but is not aware that there's something completely different in the stream. Even when adding new elements only at the end, this still breaks the serialization, because the next message element is now reading garbage. The alternative would be to keep track of the size of each message element individually, which would blow up messages for no good reason.

Currently, CAF assumes that all nodes have the exact same type announcements. If even one node fails to deserialize a message, the application is pretty much in Undefined Behavior Land. Even if a developer is insanely careful and manages to serialize upwards compatible... once you build a forwarding chain A -> B -> C, you lose information if B has an older class version.

The only valid examples I see for versioning is writing data to a disk and allow reading this data later with a newer version of the application. This requires a bit extra code by the user, but I'm actually fine with that to be honest. In fact, I think it is unlikely that one would use CAF's serializer in this case. Usually you are storing into a database or at least pick a file format like JSON or XML that allows you to read/write from non-C++ code.

**Comment by mavam** [comment]
Versioning at at per-message level neither strikes me as a reasonable choice due to the significant pessimization for the common case. It would only make sense if CAF nodes enhance the initial handshake with exchanging announced types and their versions.

But I can see that many applications would use CAF's serialization framework beyond messaging, where versioning has its merits (see VAST & Broker). Persistence is likely the most common use case here. In fact, adding version information to the serialized data is orthogonal from dispatching the serialization routines itself. For example, in VAST my serializer provides the following function:

```cpp
  template <typename T>
  auto put(T const& x) -> decltype(serialize(std::declval<Derived&>(), x, 0)) {
    auto version = derived()->template begin_instance<T>();
    serialize(*derived(), x, version);
    derived()->template end_instance<T>();
  }

  template <typename T>
  auto put(T const& x) -> decltype(serialize(std::declval<Derived&>(), x)) {
    derived()->template begin_instance<T>();
    serialize(*derived(), x);
    derived()->template end_instance<T>();
  }
```
Depending on the signature of the customization point `serialize(...)` (selected via expression SFINAE), the derived serializer retrieves the version via `begin_instance<T>` and feeds it into the function, which can then perform version-specific serialization of `T`.

An orthogonal question is how to store the version information in the serialized data stream. Here, you could imagine that each serializer provides functions to register types once, e.g., `serializer::register_type<T>(version)`. This would result into a header with type and version information. When writing out several KB or MB in binary form, say a `vector<T>`, this pays off quickly compared to serialization type version information each time the serializer hits a concrete instance of the registered type.

**Comment by Neverlord** [comment]
Persistence requires more than "just" versioning. Closing this as rejected. An eventual API for persistence may need something like this as building block, but then we're discussing this in a broader context. Besides, custom file formats using the CAF serializers can already add a header to include API / CAF version.
