### ISSUE TITLE
Build based on SCons

### ISSUE THREAD

**Issue by osblinnikov** [actor-framework/actor-framework#256]
Hello,

I impressed by the CAF libraries and would like to propose to use a SCons wrapper for building it in parallel with the existing CMake builds.

Here is the [link](https://github.com/osblinnikov/caf-workspace) to the whole workspace for CAF compilation.

With SNocs it's possible to customize the build of all the dependent projects from the command line.

snocs libcaf_io compiler=gcc platform=x64 configuration=Debug shared=1

This line above will start compilation of libcaf_io and libcaf_core (as a dependency) using provided configuration. (shared=1 means to build the projects as the shared libraries)

To use snocs you need scons, python and for cash project also libedit. To build everything run ./build.bash in the [workspace](https://github.com/osblinnikov/caf-workspace)

Please give me your opinion if it is something that is interesting for CAF project.
Thank you for reading my proposal.

**Comment by Neverlord** [comment]
Welcome aboard. :)

Thank you for your interest in CAF. We are happy to see contributions that help spreading CAF by adding support for a new platform or build system. Adding something new, however, means that someone has to maintain it. Since none of our developers is using SCons, I would (at least at the moment) rather not add your setup to the main repository. Simply because maintaining one build on our end is tedious enough.

That beging said, we can add a link to your setup to the readme and you could create a Wiki page if you are willing to extend and maintain your setup. I think it's not necessary to support *all* build options our `configure` script provides, but adding an option to build the develop branch instead of the master would be nice. Also, the `--no-*` options of the configure script can fix build issues with CAF if the compiler being used to compile CAF is different from the compiler that built Qt for instance.

**Comment by osblinnikov** [comment]
Wonderful :). I'm ready to support it myself in case of possibility to spread the goodness together.
I'll try to provide all the configure options.
If you don't mind I will keep posted in this thread.

**Comment by osblinnikov** [comment]
Hi, seems like I finished with the most of [configure options]
(https://github.com/osblinnikov/caf-workspace/wiki/Configure-CAF-build-CMake-vs-SNocs) and compiled it on Linux

I skipped `benchmarks`, `perftools` and `compiler-check` for now. If someone would need those I think it is possible to support them as well.

**Comment by Neverlord** [comment]
I don't expect many people to run the benchmarks, to be honest. :)
I'll add the readme link with the next release and update our Wiki as well with a link to your detailed SNocs options descriptions.

**Comment by osblinnikov** [comment]
Thank you Dominik!

**Comment by Neverlord** [comment]
I copied your Wiki entry [1] and edited the readme file [2] to include a link to the SCons setup. You can edit the entry in our Wiki, btw.

[1] https://github.com/actor-framework/actor-framework/wiki/Using-SNocs
[2] https://github.com/actor-framework/actor-framework/commit/315c41e9be2aab094a8e816fe05fc0b9d0e5720d
