### ISSUE TITLE
Providing a manual way to configure host id

### ISSUE THREAD

**Issue by araste** [actor-framework/actor-framework#263]
In some systems like:
- dockerized containers
- systems using distribution coordination system (like zookeeper)
- mobile devices (iOS, android)

it may be insufficient to generate a host id with a combination of root uuid and mac address. -- for some system it is unable to get them and for some system there are better alternative. 

It will be good if there is a way to configure the host id key manually before caf::node_id singleton is initialized.

**Comment by mavam** [comment]
:+1: for Docker and mobile.

I'm failing to see why a distribution coordination system could cause trouble, as it consists of multiple individual nodes with unique IDs. Maybe you can give an example?

**Comment by araste** [comment]
@mavam Right, the coordination system does not make trouble. But it is a matter of necessity and clarity; If a process is assigned to a 'role' and zookeeper makes sure that there is no other process in the system with that role, we can name the process with the role name for clean look and the log messages will be easier to read.

**Comment by Neverlord** [comment]
The purpose of the node ID is to provide, in combination with the process ID, a globally unique identifier for a single CAF instance. If CAF detects the same node ID for two instance it might (i.e. currently does not) migrate a connection to pipes instead of localhost sockets for efficiency. However, generating the node ID completely random is an option if there are too many issues with the current approach. Randomness does suffer from the birthday paradox, though. That's why we use MAC address and UUID as "seed".

On iOS, I don't see a problem with ever-changing MAC addresses, but you are of course right in the bigger picture. Still, I don't like the idea of having users to manually configure something that should be invisible to the user (we could include the hostname to the logfiles for clarity). Any suggestion what we might use instead that is portable across all platforms? Maybe a combination of OS name, hostname, and some HW-specific detail (serial number of mainboard or something like that)?

**Comment by araste** [comment]
The problem current I am suffering is; **I cannot use CAF for my iOS development**, because of caf::detail::get_root_uuid() function. It launches a new process with 'popen', which is prohibited by Apple.

For my free apps with advertisement, IDFA (advertising identifier) is the best option. For my paid apps, there is no option better than just a random UUID. I will link Core Foundation framework and use CFUUID to generate a randomly generated UUID because it provides the best way Apple supports.

And also there can be a platform that /usr/bin/awk is missing. 

Some platforms there is no option better than a random generated string and some platforms there is a platform specific way for each. We can make a bunch of macro definitions like CAF_RANDOM_HOST_ID, CAF_IDFA_HOST_ID, CAF_IDFA_DNS_HOST_ID and so on but then this project will be full of platform specific codes. To make this project neat and clean and platform neutral I thought it will be better to place the host id generating code outside the project.

Before that I may contribute a way that will work on iOS and simulators like this; 
```
#ifdef CAF_MACOS

#include "TargetConditional.h"

#ifdef (TARGET_OS_IPHONE) || (TARGET_IPHONE_SIMULATOR)

string get_host_id() {
    char sz_buffer[256];
    CFUUIDRef uuid = CFUUIDCreate(kCFAllocatorDefault);
    CFStringRef str = CFUUIDCreateString(kCFAllocatorDefault, uuid);
    CFStringGetCString(str, szBuffer, 256, kCFStringEncodingUTF8);

    CFRelease(str);
    CFRelease(uuid);
    return string(sz_buffer);
}

#else

// ...

#endif
```

But it will require an additional dependency for CoreFoundation framework and a linker flag should be added: '-framework CoreFoundation'. :)
  
My suggestion is:

1. Some platforms we know well (can access the root volume uuid and mac addresses) provide the way we know the best

2. The other platform, provide it with a generated random number with a seed containing mac, hostname and the highest resolution timer clock the platform can give.

3. For people who knows very well about this mechanism, give a manual way to set the host id to make their best.

How do you think?

**Comment by Neverlord** [comment]
Ok. I've added a function for setting the node ID via `detail/singleton.hpp` for testing. Android and iOS are now recognized via `config.hpp` and both generate a random UUID. Can you confirm that this works for you?

**Comment by araste** [comment]
Tested on Xcode 6.2, iOS 8.2, both iPhone simulator and iPhone 6. Works as expected and like a charm. Thank you very much!

**Comment by Neverlord** [comment]
Ok, thanks for checking.
