### ISSUE TITLE
Need separate config header

### ISSUE THREAD

**Issue by firegurafiku** [actor-framework/actor-framework#270]
I'm thinking on improving the build system for now, and I've noticed that it use [`add_definitions`][1] to pass some configuration flags important for conditional compilation:
```
$ grep "add_definitions" -R .
./CMakeLists.txt:  add_definitions(-D_WIN32_WINNT=0x0600)
./CMakeLists.txt:  add_definitions(-DWIN32)
./CMakeLists.txt:  add_definitions(-DCAF_LOG_LEVEL=${CAF_LOG_LEVEL})
./CMakeLists.txt:  add_definitions(-DCAF_ENABLE_RUNTIME_CHECKS)
./CMakeLists.txt:  add_definitions(-DCAF_NO_MEM_MANAGEMENT)
```
Apart from `WIN32*` stuff, other three variables belong to the CAF itself. I think we should not pass them as compiler flags, instead we should create a separate configuration header (for example, `<caf/config.h>`) using CMake's [`configure_file`][2] command, and install that configuration header alongside other library's headers. So when user tried to link his own code against the library, they can see the configuration library has build with, and have no change to pass *different* compiler flags breaking the linkage).

I've additionally checked whether all conditional compilation is located in header files, and if it was so, I'd never submit this issue, but it was wrong:
```
$ grep CAF_LOG_LEVEL -R --exclude \* --include \*.cpp
libcaf_core/src/actor_registry.cpp:# if defined(CAF_LOG_LEVEL) && CAF_LOG_LEVEL >= CAF_DEBUG
libcaf_core/src/logging.cpp:#ifndef CAF_LOG_LEVEL
libcaf_core/src/logging.cpp:  constexpr int global_log_level = CAF_LOG_LEVEL;

$ grep CAF_NO_MEM_MANAGEMENT -R --exclude \* --include \*.cpp
libcaf_core/src/memory.cpp:#ifdef CAF_NO_MEM_MANAGEMENT
libcaf_core/src/memory.cpp:#else // CAF_NO_MEM_MANAGEMENT
libcaf_core/src/memory.cpp:#endif // CAF_NO_MEM_MANAGEMENT
```

[1]: http://www.cmake.org/cmake/help/v3.0/command/add_definitions.html
[2]: http://www.cmake.org/cmake/help/v3.0/command/configure_file.html

**Comment by firegurafiku** [comment]
I've just missed the fact that such a header already exists (with obvious name `caf/config.hpp`), but acts somehow strange to me. Main `CMakeLists.txt` contains the following section:
```cmake
# read content of config.hpp
file(READ "libcaf_core/caf/config.hpp" CONFIG_HPP)
# get line containing the version
string(REGEX MATCH "#define CAF_VERSION [0-9]+" VERSION_LINE "${CONFIG_HPP}")
# extract version number from line
string(REGEX MATCH "[0-9]+" VERSION_INT "${VERSION_LINE}")
# calculate major, minor, and patch version
math(EXPR CAF_VERSION_MAJOR "${VERSION_INT} / 10000")
math(EXPR CAF_VERSION_MINOR "( ${VERSION_INT} / 100) % 100")
math(EXPR CAF_VERSION_PATCH "${VERSION_INT} % 100")
# create full version string
set(CAF_VERSION
    "${CAF_VERSION_MAJOR}.${CAF_VERSION_MINOR}.${CAF_VERSION_PATCH}")
```
But why?? Why bother with *parsing source code's preprocessors directives* (that a freaking kludge!), why not just generate that file instead? Something like the following can solve the problem:
```cmake
# set version *directly* in CMakeLists.txt
set(CAF_VERSION_MAJOR 0)
set(CAF_VERSION_MINOR 13)
set(CAF_VERSION_PATCH 2)
math(EXPR CAF_VERSION 
    "${CAF_VERSION_MAJOR} * 10000 + ${CAF_VERSION_MINOR} * 100 + ${CAF_VERSION_BUILD}")

# set other important variables,
set(CAF_ENABLE_RUNTIME_CHECKS ...)
set(CAF_LOG_LEVEL ...)

configure_file(
    "${CMAKE_CURRENT_SOURCE_DIR}/libcaf_core/caf/config.hpp.in"
    "${CMAKE_BINARY_SOURCE_DIR}/libcaf_core/caf/config.hpp")
```
where `config.hpp.in` should have content like the following:
```cpp
#define CAF_VERSION       ${CAF_VERSION}
#define CAF_MAJOR_VERSION ${CAF_MAJOR_VERSION}
#define CAF_MINOR_VERSION ${CAF_MINOR_VERSION}
#define CAF_PATCH_VERSION ${CAF_PATCH_VERSION}

#cmakedefine CAF_ENABLE_RUNTIME_CHECKS
#define CAF_LOG_LEVEL ${CAF_LOG_LEVEL}
```

I understand that you are not going to be "CMake-dependent" or even "CMake-centric", but I think if you're going, for example, to add SCons, it is *much* clearer to recreate configuration header by means of SCons then to re-do that terrible header file parsing with regular expressions.

Moreover, with my approach you may go further and get rid of hard-coded version number in your `Doxyfile`. This should work:
```
PROJECT_NUMBER = ${CAF_VERSION_MAJOR}.${CAF_VERSION_MINOR}.${CAF_VERSION_BUILD}
```

**Comment by Neverlord** [comment]
> Moreover, with my approach you may go further and get rid of hard-coded version number in your Doxyfile.

I totally agree. Hardcoding the version in the `Doxyfile` is a dreadful idea. That's why we don't do it. ;)

The `Doxyfile` is generated from `Doxyfile.in`, which has the line `PROJECT_NUMBER = @CAF_VERSION@`.

> So when user tried to link his own code against the library, they can see the configuration library has build with, and have no change to pass different compiler flags breaking the linkage).

First things first, nothing in the ABI of CAF depends on a config parameter. Whether or not memory management or logging is turned on or off doesn't matter at link time. Would it make sense to generate an additional config header from the CMake config parameters? Maybe. It would make sure that runtime checks are turned on for the header-only parts as well without requiring the user to set the flag again (ideally the user should not know about the used options of the installed CAF version).

I strongly disagree about your suggestion of setting the version via build system. Earlier versions of CAF used this strategy and I'm glad we have that gone.

**Comment by firegurafiku** [comment]
> The Doxyfile is generated from Doxyfile.in, which has the line PROJECT_NUMBER = @CAF_VERSION@.

Sorry, I didn't spot this `*.in` due to shell autocompletion. I'd put that generated `Doxyfile` into `build/` subdirectory and do not spoil source tree. So, you use `configure_file` for putting version information into Doxygen configuration and LaTeX sources (which I think is arguable: manual is *very* likely to get inconsistent with the code, Doxygen comments are less likely), but do not like using the same consistent approach for `config.hpp`.

> I strongly disagree about your suggestion of setting the version via build system. Earlier versions of CAF used this strategy and I'm glad we have that gone.

Can you describe in more details? I just cannot get in which of parallel universes it is convenient to parse header files with regular expressions? Why extracting version information from header into build system is more fun than just setting in into the build system at once? I understand that that works, but that's *ugly*. CMake is very ugly "as is", but code like that literally makes me cry when I see it.

**Comment by Neverlord** [comment]
> (...) do not like using the same consistent approach for `config.hpp`.

The consistency is that there is exactly one place where the version is defined. I don't see why putting it to the CMake side would be more consistent. Besides, putting it to CMake would violate the "one definition rule", because we would have to define it a second time for SCons and possibly for other build systems as well.

> Can you describe in more details? I just cannot get in which of parallel universes it is convenient to parse header files with regular expressions?

Regular expressions are extremely convenient. How else would you want to parse strings?

Kidding aside, we used to have a `VERSION` file for a while as well (the parsing is a bit simpler on the CMake side), but we eventually switched to the current solution. It simply works better for me as a maintainer if the version is *in* the code base and not someplace else. Btw, no, I don't consider the CMake setup as part of the code base; for me it's a nuisance that exists out of necessity. In the past I sometimes forgot to update the version before making a new release tag. Probably because I tend to ignore the "overhead files" and focus on the code base itself. At the end of the day it's just a matter of taste (of the maintainer).

I agree that storing the original build setup in a new header (that's included by `config.hpp`) is a good idea, though. It also allows us to be more aggressive with options in the future (e.g. by adding options that change the ABI).

Moving the `Doxyfile` out of the way: my original thought was to provide only the Doxyfile and let people run `doxygen` if they want to build the documentation. We added the `doc` target later for convenience. I'm not sold on whether hiding the Doxygen stuff or not is better. I'll discuss this with the others.

**Comment by firegurafiku** [comment]
> Moving the Doxyfile out of the way: my original thought was to provide only the Doxyfile and let people run doxygen if they want to build the documentation. We added the doc target later for convenience. I'm not sold on whether hiding the Doxygen stuff or not is better. I'll discuss this with the others.

In case this may help you a bit, there is how I've set it up in my project: 
```cmake
find_package(Doxygen)
if(DOXYGEN_FOUND)
    set(RVLM_FDTD_DOXYGEN_OUTPUT_DIR "${CMAKE_CURRENT_BINARY_DIR}/doxygen")
    configure_file("${CMAKE_CURRENT_SOURCE_DIR}/Doxygen.conf.in"
                   "${CMAKE_CURRENT_BINARY_DIR}/Doxygen.conf")
    add_custom_target(doxygen
        COMMAND "${DOXYGEN_EXECUTABLE}"
                "${CMAKE_CURRENT_BINARY_DIR}/Doxygen.conf"
        DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/Doxygen.conf"
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        COMMENT "Running doxygen on project sources")
endif()
```
where `Doxygen.conf.in` contains the following line:
```ini
OUTPUT_DIRECTORY = ${RVLM_FDTD_DOXYGEN_OUTPUT_DIR}
```

**Comment by Neverlord** [comment]
I'm making this (additional config header) a task. The only challenge here is to make a default header and override it if necessary during the CMake step. Volunteers welcome. ;)
