### ISSUE TITLE
Move command line parsing out of message class

### ISSUE THREAD

**Issue by firegurafiku** [actor-framework/actor-framework#273]
Should be CLI options parsing really be a part of `caf::message`? To me, this is something *completely* unrelated to message processing per se, but an utility feature. May be it would be better to put that parsing into a separate function, like that:
```cpp
auto res = caf::parse_opts(argv, argc).against({
    {"port,p", "set port", port},
    {"host,H", "set host (default: localhost)", host}
});
```

Current implementation makes `message` class contain auxiliary structures `cli_res` and `cli_arg` and quite a bunch of parsing code. Moreover, it has to perform output to `std::cout`, right from inside of `message` class!

I understand that I'm proposing a breaking change in API, but I think there is a possibility to make a soft gradual transition.

**Comment by Neverlord** [comment]
You're late to the party, since we already discussed this during the development of `extract_opts`. We did have a separate API in libcppa and deliberately choose to only provide a thin wrapper over `extract` this time around. Part of the reasoning is that we *don't* want to ship an options parser with CAF. There are a ton of CLI parsers out there that are feature-rich and more efficient. The simplistic `extract_opts` is more of a showcase for the flexibility of CAF but by no means a full-blown CLI parser. It's certainly sufficient for simple use cases such as our own examples, but you are converting an input vector to a message and then perform a not-so-cheap operation on it. We wanted to have this explicit and "in your face".
