### ISSUE TITLE
Empty response message do not get handled

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#282]
When sending a an empty message as response to a synchronous request, there exists a bug which prevents the response handler to get executed. The example below illustrates the issue.

```cpp
#include <iostream>
#include <caf/all.hpp>

using namespace caf;
using namespace std;

int main() {
  auto nullifier = spawn(
    [](event_based_actor* self) {
      self->become(
        others() >> [] { return message{}; }
      );
    }
  );
  scoped_actor self;
  self->sync_send(nullifier, "whatever").await(
    others() >> [&] { cout << to_string(self->current_message()) << endl; }
  );
}
```

**Comment by ufownl** [comment]
I test this example with the newest version of develop branch. It seems works fine.
output on my macbook
```
@<>+@unit )
```

**Comment by Neverlord** [comment]
@ufownl Are you compiling with logging enabled? Do you see the warning that `nullifier` did not respond to a sync request?

**Comment by ufownl** [comment]
I'm sorry. I forgot reviewing the log. The warning really exists. @Neverlord

**Comment by Neverlord** [comment]
Ok, thanks for checking.

**Comment by Neverlord** [comment]
So... I reviewed this issue and it's actually not a bug, but a disconnect in semantics. A message is considered a tuple, while you assume it to be something like `vector<any>`. An empty vector does make some sense, but an empty tuple doesn't. An empty tuple is equivalent to `unit` (or its terrible counterpart `void`). That's why the runtime sends no response message in this case. I know that CAF is quite "liberate" with its messages / tuples and allows slicing and merging.

Still, changing the semantics on this would be a breaking API change. For example, `optional<message> message::apply(message_handler handler);` would have to return `variant<none_t, unit_t, message>` instead to distinguish between a `void` message handler and a handler returning an empty message. This is one example of many.

An actor sends `make_message(unit)` when receiving a synchronous message that was handled without result. I cannot reproduce the case that it replies nothing. Note that even in this case no empty message is used. Am I right assuming you're "abusing" a message as a list of values for some key/value store here? In this case I would recommend you to always prefix your result with an atom. `make_message(result_atom::value, message{})` works fine.

**Comment by mavam** [comment]
I understand the vector vs. tuple issue and concur.

> Am I right assuming you're "abusing" a message as a list of values for some key/value store here?

Yes. 

> In this case I would recommend you to always prefix your result with an atom.

How about I just return `make_message(unit)` instead of `message{}`? This appears to work while keeping the client code nicer.

**Comment by Neverlord** [comment]
Sure, that's what you get anyway. Doing it on your end saves you the warning of course. :)
