### ISSUE TITLE
Allow unit test framework to supply own main function

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#305]
The current implementation ships with a `main` function, which cannot be changed by the user. Users should be able to disable the main function by defining `CAF_TEST_NO_MAIN` before including the unit test headers. (This is API-compliant with Boost Test.)

To simplify the common use case of mere hooking, we should also take the existing main function contents and add a function `caf::test::main(int argc, char** argv)` which users can execute from their own implementation of `main`.

**Comment by firegurafiku** [comment]
This seems to be quite a trivial change. You can assign me to it if @Neverlord don't mind this feature.

**Comment by mavam** [comment]
Awesome, thanks! You have green light.

**Comment by firegurafiku** [comment]
@mavam: Which branch should I use: `develop` or `topic/unit-test-framework`?

**Comment by mavam** [comment]
Since this is short, single-commit change, you can file the PR for `develop`. (We typically use topic branches only for more elaborate multi-commit changes.)

**Comment by firegurafiku** [comment]
@Neverlord 
@mavam 

I made it working. Individual tests seems to compile, but there is a problem with `caf-test` executable which bundles all unit test into a single executable: it obviously encounters "multiple definition of 'main'" error messages. I could deal with it by using anonymous namespace:
```
#ifndef CAF_TEST_NO_MAIN
namespace {
int main(int argc, char** argv) {
  return caf::test::main(argc, argv);
}
}
#endif
```
This works (possibly because anonymous namespaces imply weak linkage on GCC), but looks tricky and produces cryptic messages about unused function "::(anonymous)::main".

I could also declare `main` explicitly weak by `__attribute__((__weak__))`, but this doesn't look much better.

So, current test setup doesn't seem to be easily compatible with `CAF_TEST_NO_MAIN` feature. May be we should remove `caf-test` target entirely and just run individual tests in a cycle instead (with CMake's `add_test` command, for example)?

**Comment by mavam** [comment]
> I made it working. Individual tests seems to compile, but there is a problem with caf-test executable which bundles all unit test into a single executable: it obviously encounters "multiple definition of 'main'" error messages.

How do these errors come up? I would imagine that all that needs to be done is taking the contents of the current `main`, putting it into an inline function in namespace `caf::test`, and then adding the global `::main` conditionally based on `CAF_TEST_NO_MAIN`.

> This works (possibly because anonymous namespaces imply weak linkage on GCC), but looks tricky and produces cryptic warnings about unused function "::(anonymous)::main".

I'm surprised that it works, actually. The linker is looking for `::main` in the global namespace, see [§3.6.3](http://eel.is/c++draft/basic.start.main):

> The function main shall not be used within a program. The linkage ([basic.link]) of main is implementation-defined. A program that defines main as deleted or that declares main to be inline, static, or constexpr is ill-formed. The main function shall not be declared with a linkage-specification ([dcl.link]). A program that declares a variable main at global scope or that declares the name main with C language linkage (in any namespace) is ill-formed. The name main is not otherwise reserved. [ Example: member functions, classes, and enumerations can be called main, as can entities in other namespaces.  — end example ]

Let's aim for standard compliance where possible. CAF should only declare a (global) `main` function when `CAF_TEST_NO_MAIN` is absent.

> I could also declare main explicitly weak by __attribute__((__weak__)), but this doesn't look much better.

Agreed, not much better, and per §3.6.3, "the main function shall not be declared with a linkage-specification."

> So, current test setup doesn't seem to be easily compatible with `CAF_TEST_NO_MAIN` feature. Maybe we should remove caf-test target entirely and just run individual tests in a cycle instead (with CMake's `add_test` command, for example)?

I would rather not introduce multiple binaries. We had that in the past. They significantly increase compile and link time. The existing method of running one instance of the `caf-test` executable per SUITE works quite well, actually.

Maybe you could show us what you already have in your fork?

**Comment by firegurafiku** [comment]
> I would imagine that all that needs to be done is taking the contents of the current main, putting it into an inline function in namespace caf::test, and then adding the global ::main conditionally based on CAF_TEST_NO_MAIN.

I thought so too. But if you make `main` conditionally-controlled, you *have* to put it to `unit_test.hpp` instead of `unit_test_impl.hpp` which is the root of the troubles.

> I'm surprised that it works, actually. The linker is looking for ::main in the global namespace [...]

I'm surprised too. May be this is not-so-compliant linker :)

> CAF should only declare a (global) main function when CAF_TEST_NO_MAIN is absent.

But it's currently absent from CAF's unit tests. If we add `#define CAF_TEST_NO_MAIN` into each test source, then we would have to create an explicit `test_main.cpp` where it's not defined.
