### ISSUE TITLE
Add new maybe class for "either T or error" semantics

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#369]
Current draft of this class can be found here: https://github.com/actor-framework/fractal-demo/blob/master/caf/maybe.hpp

Relates #367 and #368.

Integrating `maybe` into CAF requires these steps:

- Remove `::with_either<X>::or_else<Y>` interface definition and `either<X>::or_else<Y>` return type
- CAF must recognize `maybe<T>` as return type and unwrap it automatically (dropping the error message for asynchronous messages)

**Comment by Neverlord** [comment]
@mavam I thought about the semantics of `maybe<T>` a bit more. `std::error_condition` provides a default constructor for creating "not-an-error" objects.

In other words, the proposed `maybe<T>` actually has three states:
- represents a `T`
- does not represent a `T`, but holds a default-generated error (i.e. is "empty")
- represents an error via `std::error_condition`

This is pretty much the semantics of `vast::result`, is it not? For CAF, this means that `maybe<T>` supersedes `optional<T>`. I'm actually fine with that and propose to simply replace `optional`. Since `maybe<T>` is a source-compatible replacement, this is simply a "find & replace" operation in the code base.

To make transition easier, I would have `optional<T>` become a (deprecated) typedef. Creating a `maybe<T>` from `caf::none` is equivalent of creating a `maybe<T>` from `std::error_condition{}`.

Here's a small snippet showcasing how the three states are useful:

```cpp
template <class T>
using iterate_fun = std::function<maybe<T&> ()>;

iterate_fun<std::string> read_file_line_by_line(const std::string& fname);

int main(int argc, char** argv) {
  if (argc < 2)
    return -1;
  maybe<std::string&> line;
  auto f = read_file_line_by_line(argv[1]);
  while ((line = f())
    std::cout << *line << std::endl;
  if (line.error())
    std::cerr << "stream error: " << line.error().message() << std::endl;
}
```

In this snippet, the function object returns `none` once end-of-file is reached to break the loop and an actual error if something goes wrong.

**Comment by mavam** [comment]
I like the idea of superseding `optional` by `maybe` in this fashion. Performance implications would be my only concern, but I don't see any. In terms of API, this trick of using a default-contructed `error_condition` allows for unifying `optional`, `trial`, and `result` in a single API:

- `optional`: either `T` or something I don't care about
- `trial`: either `T` or some sort of error
- `result`: either `T`, the default-contructed error to signal the empty state, or a specific error for an actual error.

The semantics of `operator bool`, in my opinion, should be: return `true` if and only if you have an instance of `T`. This seems to be the case in your example, but I just want to state it explicitly, because it's a sensitive issue.

A small side advantage is that you don't have to overload lifting functions and other adapters.

**Comment by Neverlord** [comment]
> The semantics of `operator bool`, in my opinion, should be: return `true` if and only if you have an instance of `T`. This seems to be the case in your example, but I just want to state it explicitly, because it's a sensitive issue.

Yes, that's the API I had in mind too.

> A small side advantage is that you don't have to overload lifting functions and other adapters.

I think it's actually a big advantage, since it makes the API a lot easier to maintain. :)

**Comment by Neverlord** [comment]
@mavam I think the context information is too simplistic when only allowing strings. By allowing `message` instead, we allow much more fine-grained insights into the cause of an error. We could keep a convenience function returning a string, though. As long as the message contains a single string, you would get that string. Otherwise, you would get `to_string(context_)`.

**Comment by mavam** [comment]
I'm fine with that, since it only adds a minimal layer of indirection to get to the string information, while providing a more fine-grained status information when needed.
