### ISSUE TITLE
local_actor::join() complexity

### ISSUE THREAD

**Issue by nq-ebaratte** [actor-framework/actor-framework#371]
Joining groups (local_actor::join) is currently linear in the number of attached pointers (subscribed groups, monitors, etc.)
This becomes a bit of a problem when joining a large number of different groups: joining N groups is O(N²).

The relevant code is in `abstract_actor::detach_impl()`: it recurses over the whole `attachables_head_` linked list.

**Comment by Neverlord** [comment]
Joining a group attaches an object to the actor that makes sure the actor leaves the group on exit (usually attachables are used for monitoring). The call to `detach_impl` (in dry mode) makes sure that an actor never joins a group twice.

This linear search obviously doesn't scale up to large number of groups, but storing all attachables in this very is very memory efficient (a single pointer per actor). So the question is whether we store groups separately or if we impose a strict order on all attachables, thereby making `detach_impl` O(log N). The latter means adding a group or monitor would have complexity O(log N) instead of O(1).

I currently lean towards storing groups differently. In any case, thanks for filing the issue.

**Comment by nq-ebaratte** [comment]
I believe that sorting the linked list would not provide much benefits: lacking random access, it cannot be searched in logarithmic complexity ?

Though it seems to me that the group itself checks if a given actor is already subscribed at subscription time (cf. local_actor::add_subscriber). Isn't the check of the return value enough to avoid "double subscriptions" ?

**Comment by nq-ebaratte** [comment]
Indeed, I rely a lot on groups to broadcast information between (sets of) actors; according to their state they join and leave group quite often. Nevertheless, the only CPU spike I saw was on joins, specifically because my actors join a lot of groups upon initialization; the following joins/leaves are an order of magnitude less frequent.
Though others might have different use cases.

**Comment by Neverlord** [comment]
Join and leave have both complexity O(log N) in 0.14.4. This should solve the CPU spikes you've seen.

**Comment by nq-ebaratte** [comment]
Nice, thanks !
