### ISSUE TITLE
Fault tolerance in c++ actor framework

### ISSUE THREAD

**Issue by ngocthanh1389** [actor-framework/actor-framework#372]
Dear all
I want develope a high available C++ server and found interesting CAF. I am new to actor model, so I maybe wrong.
I read manual but not find fault tolerance section similar Erlang. I want ask about that. When actor crash how my program dont crash?
I coded a simple program to test. When actor crash (divide 0) process crash too.
Thanks for listening, sorry about my bad English.

Thanks and best regards
ThanhVM.

**Comment by mavam** [comment]
> When actor crash how my program dont crash?I coded a simple program to test. When actor crash (divide 0) process crash too.

In C++, you're executing native instructions. Unlike Erlang, C++ has no "safety net" VM which can catch a crash. Therefore, if your C++ program exits because of a memory safety issue or due to undefined behavior, there's nothing CAF can do about it. In the CAF manual, we mean use "crash" to refer to non-normal actor *termination*---without violating the underlying language invariants.

**Comment by ngocthanh1389** [comment]
Thanks for that detailed reply.

**Comment by Neverlord** [comment]
FWIW, you can at least partially protect an application against unrecoverable faults is by splitting it into multiple processes. For example, you can have a main process that is responsible for taking user requests and forwarding them to a set of workers. Each worker than lives in its own process, possibly distributed in the network. In this way, failing workers don't take your whole application down and you can re-distribute failed workers. You still need to make sure your main process won't crash with segfaults or divide-by-zero erros, of course.

Hope that helps. I'll close the issue, but please feel free to ask any follow-up questions here.
