### ISSUE TITLE
Requests multiplexing in event-based actors

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#378]
A common design pattern in CAF is to have an actor supervise a set of actors by delegating incoming jobs. These supervisors cannot make use of `request().then()`, because this would "block" the supervisor until a worker has finished its job by suspending its regular behavior.

A solution to this problem is to give requests a second, non-blocking alternative to `.then` that does not suspend its regular behavior.  For example `self->request(...).multiplex(...)` or `self->request(...).async(...)`.

Since 0.15 already makes quite a lot of breaking changes, we also could rename `.then` to have `.sync()` and `.async()`. Alternatively, we could use `.then` for the multiplexing and `.await` for the current suspend-until-result-arrives semantics (we should then rename `.await` for blocking actor to something else, e.g. simply `request(...).receive(...)`).

I think `.then` and `.await` make the most sense, but could be confusing for users when upgrading to 0.15. Opinions?

**Comment by mavam** [comment]
In general, I quite like this proposal. In places where I use the forward-to-spawn idiom and do not really need the concurrency, a non-blocking `.then` would come in handy and make the code much easier to understand.

> A solution to this problem is to give requests a second, non-blocking alternative to .then that does not suspend its regular behavior. For example `self->request(...).multiplex(...)` or `self->request(...).async(...)`.

Could you elaborate on the messaging semantics? IIRC, `.then` created a one-shot handler for a specific message ID. What happens when multiple messages are inflight with `.multiplex`? Would the runtime maintain a mapping from message IDs to callbacks?
 
> I think `.then` and `.await` make the most sense, but could be confusing for users when upgrading to 0.15. 

Naming-wise, this makes most sense to me. I would not re-introduce the word `sync`, which we just got rid of due to confusion. Using `receive` instead of `await` as blocking one-shot continuations would also be consistent with the top-level `self->receive`, i.e., users know that when a `receive` is involved, there's true blocking.

**Comment by Neverlord** [comment]
> Would the runtime maintain a mapping from message IDs to callbacks?

Yes. An actor would have three "sets" of behaviors: (1) its regular behavior stack, (2) the stack of awaited responses, and with this proposal (3) a map `{message id => callback}` for "concurrent" response handlers.

> In places where I use the forward-to-spawn idiom (...) make the code much easier to understand.

Absolutely. This idiom needs to die. :)

> I would not re-introduce the word `sync`, which we just got rid of due to confusion.

Agreed. After thinking a bit more about it, I believe changing the semantics of `.then` is not that big of a deal, as this "concurrent" work flow is probably more intuitive.

**Comment by mavam** [comment]
> Absolutely. This idiom needs to die. :)

Good. Recently, I introduced a subtle bug because it's very easy to inadvertently access shared state in the spawned job actor. With the new `.then`, this wouldn't have happened.

> I believe changing the semantics of `.then` is not that big of a deal, as this "concurrent" work flow is probably more intuitive.

In fact, other asynchronous actor model implementations (e.g., libprocess) also use `.then` in the "true" asynchronous manner as you propose it now.
