### ISSUE TITLE
Provide a "dot operator" for actor handles

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#380]
Combining two actors handles using "dot operator" semantics is an important building block for building pipelines of actors. The current proposal is to use `operator*`, since `operator.` cannot be overloaded in C++ and `operator|` is reserved for UNIX-like pipelining in future CAF releases.

**Comment by Lingxi-Li** [comment]
Currently, a composed actor is impersonating the identify of its first constituent. I don't quite understand this design. Maybe, it's because `composed_actor` is intended to be an actor decorator. If so, then I don't think it should be intended as such. Impersonations like this could lead to confusions when the lifetime of a composed actor does not match that of the impersonated actor, i.e., the first constituent. Specifically, a composed actor exits when either constituent exits or it could be exited all alone, independent of its constituents. Because of this, it is appropriate to give a composed actor its own identify.

Also, it seems possible to trim `composed_actor` by deriving from `monitorable_actor` instead of `local_actor`. To summarize, we should have composed actors as independent light-weight actors with own identifies. If you think the idea is good, I'm going to work on a PR.

**Comment by Neverlord** [comment]
> Currently, a composed actor is impersonating the identify of its first constituent. I don't quite understand this design. Maybe, it's because composed_actor is intended to be an actor decorator. If so, then I don't think it should be intended as such. Impersonations like this could lead to confusions when the lifetime of a composed actor does not match that of the impersonated actor, i.e., the first constituent. Specifically, a composed actor exits when either constituent exits or it could be exited all alone, independent of its constituents. Because of this, it is appropriate to give a composed actor its own identify.

In the first draft of this feature, composed actors used to have their own identity. The reason I changed it to the current behavior is twofold. First, the composed actor really is a decorator for `g`. You send `g` a message that says the response goes to `f` (which in turn will respond to the original sender). The fact that `h`  is internally linked to both `f` and `g` is merely an optimization. Second, identical compositions should compare equal, i.e., `h = f*g ^ j = f*g => h = j`. I don't see a way to ensure that each composition gets the same actor ID assigned. Comparing actors should remain a lightweight operation that keeps a total order.

I agree that `(f*g) != f && (f*g) == g` looks strange. Further, one couldn't store `h` and `g` in a map, even though sending a message to `h` clearly isn't the same as sending a message to `g`. Falling back to the last implementation on the other hand would mean that you could have `g`, `h` and `j` in the same map, whereas `h` and `j` definitely should be considered identical. The same applies to bound actors, btw.

By the way, the current implementation actually composes `(f*g) = g(f(x))`, as pointed out by @mavam in chat (on the todo list to be fixed).

> Also, it seems possible to trim composed_actor by deriving from monitorable_actor instead of local_actor.

A composed actor has a behavior for handling exit messages. A monitorable actor does not have the `do_become` member function and thus cannot have any behavior.

> To summarize, we should have composed actors as independent light-weight actors with own identifies.

How would you guarantee that identically composed actors are compared equal without imposing a performance hit on the operators `==`, `!=`, `<`, etc. for `actor`? Making this change would also mean the same should apply to bound actors.

**Comment by Lingxi-Li** [comment]
So, the main issue lies in actor comparisons. You suggest that the comparison be based on behaviors, and actors with identical behavior should compare equal. But could you implement the semantics consistently? What if I manually spawn two actors and initialize them with the same behavior. How would you guarantee that they compare equal? I see no means for CAF to check consistently whether two actors have identical behavior or not. In the current version, even two actors with different behaviors may compare equal. For example, two actors composed differently but both have actor `g` as their first constituent actor. This defeats the whole idea behind behavior-based comparison. So, basically, there is no way to implement behavior-based comparison consistently. I would say that instead of behavior-based comparison, identify-based comparison would be more reasonable. That means you could have two actors with identical behavior but compare unequal, for they are distinct actors. Identify-based comparison is easy to understand and implement. It should be the semantics a user would expect first, when talking about actor comparisons. If users do need to check whether two actors have the same behavior, they should design and implement the mechanisms their own. Users have specific knowledge of their particular use cases, and may be able to implement consistent behavior-based comparisons. CAF, as a framework and library, does not do that.

With respect to the trim of `composed_actor`, I see no need for the `do_become()` member function. System messages like `exit_msg` could be handled on-the-fly (and synchronously) during the call to `enqueue()`. This would be more efficient.

**Comment by Neverlord** [comment]
> You suggest that the comparison be based on behaviors

No.

I suggest that compositions should be referentially transparent, i.e., `h = f*g ^ j = f*g => h = j`. Unlike ordinary actors, actor compositions are not bound to any CAF node. When sending to a composed actor, you always get the shortest path to `g` and then the shortest path to `f`. Even when passing `h` around in a distributed system. This means composed actors behave differently during serialization, i.e., you create new composed actors and never make a proxy to a remotely created composed actor.

A simple example: you send `h` to an actor which only sends you back the handle. You expect that the received handle compares equal to `h`, do you not? When sending the handle to a remote actor instead of a local one, this wouldn't be the case in your proposed implementation.

> could be handled on-the-fly (and synchronously) during the call to `enqueue()`

This would execute cleanup code in the context of the sender, resulting in a data race when receiving exit messages in parallel.

**Comment by Lingxi-Li** [comment]
I guess I will need some time to digest what you have said. I haven't dived into the network part yet.

> This would execute cleanup code in the context of the sender, resulting in a data race when receiving exit messages in parallel.

`monitorable_actor::cleanup()` is thread-safe. So, concurrency should not be a problem here.

**Comment by Neverlord** [comment]
I think a reasonable compromise for "full" referential transparency could be to drop the `h == j` requirement and "only" make sure that serializing a composed actor back and forth still compares equal to the original. I think that preserves most desirable properties while remaining lightweight enough. When changing `composed_actor`, it only makes sense to give `bound_actor` the same treatment: unique ID, but serializing a decorator keeps the composition intact (the deserialized composition behaves exactly as if it were created locally, except that it has the original actor and node ID).

> `monitorable_actor::cleanup()` is thread-safe. So, concurrency should not be a problem here.

You are right. As long as the code only accesses the message itself and `monitorable_actor::cleanup`, there's no need to inherit from `local_actor`. The member function `cleanup` is not required to be thread-safe when overriding it. That's why I didn't go this route initially.

**Comment by Lingxi-Li** [comment]
I've looked into the implementation of `bound_actor`, and I couldn't help asking the question: could `composed_actor` be implemented like the light-weight `bound_actor`? Non-system messages are modified and forwarded, and system messages are forwarded directly. And to maintain current behavior, in the constructor, we link `first` and `second`. We also override methods in `abstract_actor` and forward them to `first`. This more effectively erases the identity of the decorator and improves performance. Is this good? It even seems possible to factor a `decorator_actor` from which both `bound_actor` and `composed_actor` derive from.

**Comment by Neverlord** [comment]
> This more effectively erases the identity of the decorator and improves performance. Is this good?

As of our discussion here, I would say no. Both the composed and the bound actor should have their own identity and not compare equal to a "decorated" actor. This means both kinds of actors can inherit from `monitorable_actor` and only need to override `enqueue`.

**Comment by Lingxi-Li** [comment]
I think I can work on this, and fix the dot composition order issue along the way.

**Comment by Neverlord** [comment]
:+1:
