### ISSUE TITLE
Reusing TCP connections between nodes

### ISSUE THREAD

**Issue by nq-ebaratte** [actor-framework/actor-framework#390]
When opening several `remote_actor` (or remote_group) from a node A to the same node B, a new TCP connection is opened for each remote actor.

This really can be suboptimal if several actors need to have handles to each others across processes, though they aren't exchanging much messages.

**Comment by Neverlord** [comment]
TCP-connections are already re-used, i.e., CAF will only maintain a single TCP connection per connected node. However, each call to `remote_actor` triggers a connection, even if it is closed immediately afterwards (in case it's a second connection to an already known host).

The BASP broker should store known hostname/port combinations to actors it is already connected to in order to bypass unnecessary connection in the first place.

**Comment by Neverlord** [comment]
@nq-ebaratte the issue should no longer occur in the fixed version. Backporting this change to 0.14 is probably not straightforward. Can you migrate to the 0.15 syntax in a reasonable time frame to verify this on your end?

**Comment by nq-ebaratte** [comment]
I can certainly migrate to 0.15. Though it'll be harder for me to verify the patch since I am now caching known remote actors locally. I'll let you know if anything strange still happens :+1:
