### ISSUE TITLE
Propose to hide `scoped_actor` by default

### ISSUE THREAD

**Issue by Lingxi-Li** [actor-framework/actor-framework#402]
`scoped_actor` is quite explicit and tangible, with a lifetime well-defined by RAII. One key use case for registering actors is to `await_all_actors_done()` upon destruction of an actor system. This does not apply to scoped actors, for a scoped actor is guaranteed to exit before destruction of the hosting actor system. As such, I think it should be hidden by default and thus does not interfere with the registered actor count. Registration should be something for the implicit and less tangible actors whose lifetime is not clear at first sight. This proposal needs revision to some unit tests as well.

**Comment by Neverlord** [comment]
I don't think the assumption that `scoped_actor` always lives in a sub-scope of `actor_system` is true. A simple use case where this isn't the case is when having a `scoped_actor` as member in a class. Any object of that class can live on the heap, potentially having a complex lifetime managed by some third-party library.

A potential performance gain is negligible, but this change could cause undefined behavior that is really hard to debug. I don't expect users to know about the `hide` flag, since it's meant for in-library use only. The manual doesn't even mention actor hiding, and for good reason.
