### ISSUE TITLE
Feature request: add interface to get a remote actor's IP address and port

### ISSUE THREAD

**Issue by rsmmr** [actor-framework/actor-framework#419]
For tracking connections between nodes, it would be very helpful to be able to get a remote's actor's IP address and port. I figured out a hack to get that information, but that's not thread-safe:`

     caf::actor p;
     [...]
     auto node = p->node();
     auto mm = caf::io::middleman::instance();
     auto basp = mm->get_named_broker<caf::io::basp_broker>(caf::atom("BASP"));
     auto ch = basp->state.instance.tbl().lookup_direct(node);
     auto addr = basp->remote_addr(ch);
     auto port = basp->remote_port(ch);

**Comment by Neverlord** [comment]
Not properly documented yet (as many features in 0.15), but here's an example use case:

```cpp
node_id x = ...;
auto mm = system.middleman().actor_handle();
self()->request(mm, get_atom::value, x).receive(
  [&](const node_id& nid, const std::string& addr, uint16_t port) {
    assert(nid == x);
    cout << "address: " << addr << ", port = " << port << endl;
  }
);
```

If no direct connection exists, you'll receive an empty string and port 0.

**Comment by mavam** [comment]
If I have lost the connection to `x`, does this still work to get the address and port information?

I'm implementing a reconnect mechanism from the DOWN handler, from where I use the node ID from the actor address.

**Comment by Neverlord** [comment]
No, the middleman does not keep state longer than necessary.

**Comment by mavam** [comment]
Okay, then I will keep the endpoint information at a higher layer manually.

**Comment by Neverlord** [comment]
@mavam I think this is a feature many CAF users could want. @josephnoir is going to improve the network layer in the next couple of weeks (months?). Ideally, this should have a configurable reconnect interval. There are of course open questions:
- should CAF cache messages to re-send them after a disconnect with short downtime?
- if the node comes up "fresh", how does CAF detect this + terminates all invalidated proxies
- can CAF deal with this scenario for indirect connection?
- etc.

Implementing this on a higher level can result in inconsistent system states. If A and B are connected to C and only the connection A <-> C goes down, A will see all actors of C die, while B doesn't. Just something to consider.

**Comment by mavam** [comment]
> Ideally, this should have a configurable reconnect interval.

Yep, that's what I'm planning for as well.

> should CAF cache messages to re-send them after a disconnect with short downtime?

I would imagine many users would appreciate some resilience to network downtime. At the same time, there's no one-size-fits-all answer. With buffering, you're quickly in OOM land for large or numerous message volumes. In the Bro context, we have messages typically at the order of 100s of bytes, but want to support rates ideally up to 100K/sec. If a node goes down, it's not tractable to buffer for very long. Therefore, the user must define its capacities, e.g., provide an upper bound on the number of messages to buffer while reconnecting.

Another aspect concerns the granularity of buffering: whether to do it at the actor or actor-system level.

> if the node comes up "fresh", how does CAF detect this + terminates all invalidated proxies

I don't understand the invalidation procedure. If one node goes down, the other nodes wouldn't invalidate their proxies, but first mark them as disconnected, no? 

> can CAF deal with this scenario for indirect connection?

There are two scenarios to distinguish here: if the intermediate node goes down when the node hosting the actor goes down. The first case is not much different from standard reconnecting: just attempt to connect to the intermediary again.  The latter case is trickier, because now the intermediary node is burdened with the task of reconnecting. If buffering takes place in addition, then things could get quickly unpredictable performance-wise.

I think this discussion warrants a separate ticket.
