### ISSUE TITLE
Idea about adopting a LIFO approach in work stealing

### ISSUE THREAD

**Issue by Lingxi-Li** [actor-framework/actor-framework#459]
I recently read about the thread pool in .NET and find it extremely similar to the working stealing model in CAF. The interesting thing is that .NET has adopted an optimization that CAF hasn't. In CAF, we note that `queue.append(job)` is called in `work_stealing::external_enqueue()`, and `queue.take_head()` is called in `work_stealing::dequeue()`. So, this is basically a FIFO approach. While .NET once did the same, it has moved to LIFO approach since version 4.0. The reasoning is as follows (quoted from *Programming C# 5.0* by Ian Griffiths):

> The most recently queued items are the ones for which the relevant state is most likely still to be in the cache, so the CPU will be able to execute them more quickly if it handles them immediately than it would if it always handled the oldest items on the queue first. Serving items in the order in which they were created may seem fairer, but it will tend to reduce throughput—once the queue grows beyond a certain length, in-order handling guarantees that everything will run slowly, because the CPU is forever working on items for which the relevant state is no longer in the cache.

So, maybe CAF should also move to a LIFO approach? With this modification in place, `work_stealing::external_enqueue()` would have the same semantics as `work_stealing::internal_enqueue()` that is called by `worker::exec_later()`. In other words, instead of limiting the scope of the LIFO strategy to just `worker::exec_later()`, we try to apply it universally.

**Comment by Hamdor** [comment]
That sounds interesting, maybe we can benchmark a FIFO vs a LIFO approach with `perf`.

**Comment by mavam** [comment]
Yep, interesting. Benchmark results will ultimately decide where this goes. Would you be interested in driving this forward and running the benchmarks, @Lingxi-Li? This could also become a nice quick blog post on the CAF developer blog, illustrating how to do a idea-implement-measure cycle.

**Comment by Neverlord** [comment]
>  In other words, instead of limiting the scope of the LIFO strategy to just `worker::exec_later()`, we try to apply it universally.

Let me shed some light on the design of CAF's scheduler.

When designing a general purpose thread pool, you cannot make assumptions on the things you are scheduling. After creating a "runnable" (often a simple `std::function<void ()>`), the associated objects are "hot" in your cache. Since some caches are shared between processors, you can even get cache hits if you enqueue your new job to a different worker thread. So it naturally makes sense to have a LIFO queue in a general purpose scheduler. You have no knowledge of the tasks in your queue, but you can assume that your chances are relatively high to get cache hits on the new runnable.

So why the LIFO/FIFO separation in CAF?

First, we do not schedule *tasks*. We schedule *actors*. An actor can process multiple messages in a single shot. This has the potential to starve others or cause arbitrary delays for others. This is the reason we have the "throughput" parameter. Once an actor reaches the maximum of messages it is allowed to consume in a single shot, it will be enqueued as new *last* element in the queue, giving all waiting actors a chance to run on the CPU. This is the first major difference. We do not schedule tasks that do something and then get deleted. Actors can get re-scheduled and stay alive independently from the work queues.

Second, we know for a fact that items in our queue are related to each other. Assume you have two actors A and B, that play ping pong. A receives ping and replies with a pong, causing B to get enqueued to the queue (LIFO). If for some reason, C is now enqueued while B is enqueued but A didn't return from its handler yet, then we trash our cache. Maybe we have some hits on level 2 or 3 for C, but we know for a fact that B is hot.

Actors end up in a worker queue as a direct result of interaction with another actor from that queue. Either via spawning or message passing. So what is more likely, that the top of our queue is hot or that some other work item from another thread is hot?

When do we use `external_enqueue`, anyways? Only when sending messages to or spawning actors from contexts outside of our work-stealing context. This is usually when starting the first actors in `main` or when interacting with detached actors. In the former case, our queues are empty, so it makes no difference. In the latter case, it is much more likely that we get better cache hits for items in our queue. Simply because we have the knowledge that items in our work queue are related to each other.

**Comment by Lingxi-Li** [comment]
Thanks for the detailed explanation. It clarifies things out :)
