### ISSUE TITLE
Add option to crash on unhandled exception

### ISSUE THREAD

**Issue by ukreator** [actor-framework/actor-framework#465]
While working with a server process written with CAF, we've come across an issue with exceptions. Once in about a few months boost::asio throws an exception somewhere. Currently we use ```set_exception_handler``` for every actor in the system which just calls ```abort()```. And since the custom exception handler accepts std::exception_ptr, there's no way to restore the call stack to debug the problem.

It would be great to have a way to let an actor not to handle exceptions at all and just crash.

**Comment by Neverlord** [comment]
So, basically a `CAF_NO_EXCEPTION` compiler flag? I could see that being useful when compiling CAF for small devices (with little or no exception support) as well.

If the exception is thrown from ASIO, you should at least be able to re-throw and catch it as `boost::exception`. This at least gives you function, file name, and line number.

**Comment by ukreator** [comment]
Yes, that global compile flag would be enough. We treat any unhanded exception (in actors) as a developer error that needs to be fixed ASAP.

Thanks for the hint about boost::exception. I've checked what kind of output boost::asio generates while throwing exception and it's different from what we see in production. We see no function name in the string returned from std::exception::what() (always "Invalid argument" in our case). So apparently it's POSIX call fails somewhere (probably c++ std library or ASIO internals).

**Comment by Neverlord** [comment]
Thinking a bit more about this: some API calls would have to change for this. For example, `publish` and `remote_actor` currently throw exceptions. Either the functions return `optional` or we add a second set of functions that do not require exceptions and disable the throwing ones when building with exceptions disabled.

**Comment by mavam** [comment]
I would prefer to avoid exceptions when possible. In the case of simple functions like `publish` and `remote_actor`, why do they need to throw in the first place? There's no deeper context to be propagated. The serialization framework is the only place right now where exceptions are justified, because the free functions return `void`.

**Comment by Neverlord** [comment]
I think this is a good opportunity to make CAF exception-free. This allows us to port CAF to embedded devices that simply do not support exceptions. The only thing `CAF_NO_EXCEPTION` would need to remove is the `try/catch` surrounding message handlers.

Speaking of `remote_actor` and `publish`, both functions should be able to communicate errors to the user. Hence, `optional` is not a good fit. Unearthing `maybe` is not ideal either, because neither function are allowed to return *nothing*. It's either a valid result or an error.

I think we should adopt Alexandrescu's `expected` with the tweak that it does store either a value or a `caf::error` instead of storing a either a value or an exception.

The following changes would be required in CAF:

| Function Signature             | Proposed Change                             |
|--------------------------------|---------------------------------------------|
| uint16_t publish(...)          | =&gt; expected&lt;uint16_t&gt; publish(...)          |
| actor remote_actor(...)        | =&gt; expected&lt;actor&gt; remote_actor(...)        |
| Handle typed_remote_actor(...) | =&gt; expected&lt;Handle&gt; typed_remote_actor(...) |
| void quit(...)                 | =&gt; move to event-based actors?              |
| void set_error_handler(...)    | ?                                           |
| void set_down_handler(...)     | ?                                           |
| void set_exit_handler(...)     | ?                                           |

The hard part is `quit` and the handlers. Currently `quit` throws when called from a blocking actor. This is necessary to unwind the stack and properly "shutdown" the thread after receiving an `exit_msg`.

We could remove `error_handler`, `down_handler`, and `exit_handler` from the API of blocking actors and have users handle all messages manually. I don't hate this idea, because the primary use case for blocking actors is `scoped_actor`. Mixing system messages with ordinary messages in this case makes some valid use cases simpler to implement.

On the other hand, this diverges the API of blocking and event-based actors. However, I see the primary use case in `scoped_actor` and don't mind this too much.

Opinions or more ideas?

**Comment by mavam** [comment]
> I think we should adopt Alexandrescu's `expected` with the tweak that it does store either a value or a `caf::error` instead of storing a either a value or an exception.

That's precisely the semantics of VAST's `trial<T>`, by the way. I prefer the name `trial` over `expected` for two reasons: first, it's much shorter. Second, and more importantly, the naming resembles a `try { }` block, which makes for a very intuitive association.

> On the other hand, this diverges the API of blocking and event-based actors. However, I see the primary use case in `scoped_actor` and don't mind this too much.

If `scoped_actor` is the only show stopper, then I wouldn't mind removing the system handlers either.

What's your take on the serialization functions, which currently can only throw to signal an error? Likewise, a future printable/parseable concept would also have to propagate error context.

**Comment by Neverlord** [comment]
> That's precisely the semantics of VAST's `trial<T>`, by the way. I prefer the name trial over `expected`

I like `expected` and `optional` better, because they are adjectives. "I expect to return an integer" makes sense, so does "I optionally return an integer". "Trial" is a noun and sounds a bit too much like we're in court. ;)

`try<int>` isn't valid syntax, otherwise the verb form would make more sense: "I try to return an integer". "Promise" would be a good name, but it's already taken.

Also, `expected` is known to many C++ developers by now. There was a proposal for `std::expected`, so maybe we see this standardized eventually (seems like it has been voted out, for now).

> If `scoped_actor` is the only show stopper, then I wouldn't mind removing the system handlers either.

Blocking actors in general are, but `scoped_actor` is the primary use case.

> What's your take on the serialization functions, which currently can only throw to signal an error?

Returning something other than `void` from `serialize` would mean to throw away the possibility of Boost.Actor, since we can no longer provide a compatible interface. However, an implementation based on `reflect` (see #470) could very well do better. I'd say we keep `serialize` as it is for backward/Boost.Actor compatibility and move on internally with `reflect`. That would mean we need to slightly change the `reflect` API.

Current proposal:

```cpp
template <class Mirror>
void reflect(Mirror& mirror, named_actor_config& x, const unsigned int) {
  mirror & meta::type_name("named_actor_config");
  mirror & x.strategy;
  mirror & x.low_watermark;
  mirror & x.max_pending;
}
```

Alternative:

```cpp
template <class Mirror>
error reflect(Mirror& mirror, named_actor_config& x, const unsigned int) {
  return mirror(meta::type_name("named_actor_config"),
                x.strategy;
                x.low_watermark;
                x.max_pending);
}
```

The `mirror` simply has a variadic call operator, recursively applying all arguments and returning on the first error (a default constructed `error` represents no-error).

And with a bit template magic, we can support both `reflect` and `serialize` and leave the choice to the developer.

**Comment by mavam** [comment]
> I'd say we keep `serialize` as it is for backward/Boost.Actor compatibility and move on internally with `reflect`.

What would make sense to is keeping the existing serialization API for Boost compatibility, but also allowing the reflection "concept" as an alternative mechanism to make types serializable.

Regarding the reflection API, I like a traits-based approach, except for the namespace nuisance: when specializing a meta trait, it has to be in CAF's namespace. For that reason, I could see a free-function-based solution being more convenient.

Of the two proposals, the latter looks more appealing to me. Though I wonder if we can make more assumptions about `Mirror` so that we don't have to cram meta data and instance data all into a single function call. It looks a bit crowded to me.
