### ISSUE TITLE
Can't send() a caf::optional<caf::actor>

### ISSUE THREAD

**Issue by ebaratte** [actor-framework/actor-framework#507]
Trying to send an optional<actor> fails with a compile error:

    void hello_world(event_based_actor* self, const actor& buddy) {
        caf::optional<caf::actor> opt;
        self->send(buddy, opt);
    }

Fails with: 

        actor-framework/libcaf_core/caf/actor.hpp:175:3: error: ‘constexpr caf::actor::actor()’ is private
        actor() = default;
        ^
        In file included from actor-framework/libcaf_core/caf/message.hpp:32:0,
        [snip]
        actor-framework/libcaf_core/caf/optional.hpp:287:30: error: within this context
        typename optional<T>::type tmp;

Indeed, the `inspect` specialization for `optional` deserialization constructs a default T object. 

On a related note, it is not possible to send a `std::unordered_map<T, caf::actor>` because of the `fill_range()` function

**Comment by Neverlord** [comment]
Thank you filing the issue.

After thinking about this and discussing it, we think it is for the better to drop the non-null guarantee again. Message types in CAF are required to be serializable, default constructible, and copy constructible [1]. Fundamental types should not break this by working around the requirements. While non-null handles have nice properties and allow cleaner code in some places, they ultimately have too many downsides.

This means you don't need `optional<actor>` in the first place, because `actor` is default constructible again. Sending messages to invalid handles is once again a no-op (as it used to be in CAF <= 0.14). The `develop` branch contains the fix, i.e., gives `actor` and `typed_actor` their default constructors back. `unsafe_..._init` and `.unsafe()` are now deprecated.

[1] http://actor-framework.readthedocs.io/en/develop/MessagePassing.html#requirements-for-message-types

**Comment by ebaratte** [comment]
Great !
