### ISSUE TITLE
Conan recipe

### ISSUE THREAD

**Issue by sourcedelica** [actor-framework/actor-framework#515]
The [Conan package manager](http://conan.io) is starting to see a lot of uptake.    I've created a [proof of concept recipe](https://github.com/sourcedelica/conan-recipes/tree/master/caf) for it and [uploaded](https://www.conan.io/source/caf/0.15.1/sourcedelica/testing) it to the Conan repo.  It was pretty easy as Conan integrates well with CMake projects.  But it would be good to have an official set of packages.

**Comment by Neverlord** [comment]
Thanks for taking the time to make a proof of concept for this! I have couple of questions:

* Is the proof of concept ready to go as-is? If not, what would you say is missing?
* Does conan provide convenient config parameters or is it easier to provide separate packages for submodules such as `libcaf_python`?
* Are there any tweaks required to get things running on Windows?
* What do we need to do on our end? Merely a new repository for hosting the `conanfile.py` and an official CAF account over on `www.conan.io`? Or does conan require tweaks to the `CMakeLists.txt` like BiiCode did in order to function properly?

**Comment by sourcedelica** [comment]
The things that I think need to be added:
- Add more options.  The only option currently is whether to use shared libraries or not (see line 26).  Conan is flexible in terms of adding other options which can be translated directly into `configure` parameters.  It can also provide those options to the clients of the package.
- On Linux I ran into a problem where, although the GCC build of CAF uses `libstdc++11`, that did not carry over to the test package.  When I built the test package I got a link error because it was using `_GLIBCXX_USE_CXX11_ABI=0`.  I have an outstanding [question](https://github.com/conan-io/conan/issues/551) in their issues on how best to handle this.  You can handle it manually by always building the CAF package with the Conan command line flag `-s compiler.libcxx=libstdc++11` but it requires you to remember that.  If it can be automated that would be good but if worse comes to worst it would need to be documented.
- Speaking of the test package, I manually copied some files from `libcaf_{core, io}` tests to the test package to run some tests when the test package is built.  You'll want to decide what tests you want to run when testing the Conan package, and if those tests are special to the test package (basically just a smoke test) or automatically copied from the source tree.  The tests that are there in the test package are specific to 0.15.1 and will get out of date quickly.   I have a related [question](https://github.com/conan-io/conan/issues/546) in their issues about this.

The "test package" is a feature of Conan for testing packages.   You setup a client package in the `test_package` subdirectory of the directory where the main package recipe is and the run `conan test_package`.

I haven't tested CAF on Windows but if it builds the same way as on Mac and Linux (`configure` + `make`) it should work fine with the existing Conanfile.

I think that's all you would need to do.   You wouldn't even necessarily need a new Github repo if you didn't want to though that would probably be cleaner.

I didn't have to make any tweaks to the CAF CMake configuration for the proof of concept.  What change did BiiCode require?

**Comment by Neverlord** [comment]
> I haven't tested CAF on Windows but if it builds the same way as on Mac and Linux (configure + make) it should work fine with the existing Conanfile.

The configure script requires `/bin/sh`, so it won't work on Windows (without Cygwin). However, the script simply calls CMake. It's easy to replace the `configure` setup with CMake directly. In any case, having only Linux + macOS support is fine by me. Windows users are free to submit patches. ;)

> The tests that are there in the test package are specific to 0.15.1 and will get out of date quickly.

Since you have done most of the heavy lifting already and have reached out to fix outstanding issues: are you OK with shipping this under CAF license(s) once the testing and Linux issues are solved? Then I would simply fork your recipe into an official CAF repository and link it to an official recipe on `conan.io`. In case you prefer a "clean" repo, I can also create an empty one with you as contributor.

We can still add more config options later or wait for contributions of users that actually need them in the first place.

> I didn't have to make any tweaks to the CAF CMake configuration for the proof of concept. What change did BiiCode require?

Nevermind, seems like that wasn't the case. We only needed a `biicode.conf` and `ignore.bii` (here is the [patch](https://github.com/actor-framework/actor-framework/commit/4fdd363c954490539046118b11195b49e92649ab) that removed Biicode support).

**Comment by sourcedelica** [comment]
A clean repo would probably be better as I will be adding more recipes for other libraries to this one.  I'm happy to contribute the code.

One thing I forgot to mention, another thing that Conan has is [conan-package-tools](https://github.com/conan-io/conan-package-tools), a system that will build versions for all of the different combinations of compiler versions, etc. using Travis or Appveyor.  That's something to consider, though it doesn't have to be done initially.

I have an answer for the ABI question and I'll update the Conanfile for it.  It will autodetect whether the current system has the old GCC C++ ABI or the new one, and check to see if the settings that were passed in match.  If not, it will throw an exception to tell the user to use the correct settings.

**Comment by sourcedelica** [comment]
The ABI issue is fixed, and I have a general solution in place for the package test.

The package test (aka `test_package`) now does a shallow, sparse clone of the repo, copies all of the tests from `libcaf_core` and `libcaf_io`, then compiles and runs them.  They recommend that we cut down the number of tests to the minimum needed to verify that the package has all the right bits (headers and libs).   That way a CI setup with a lot of combinations of platforms and compilers will run as fast as possible.   Basically a smoke test for CI.  Which subset of test files do you think we should include?   

We also need to decide on which options we should support.  Right now it's hardcoded to static only.  So we need an option for dynamic.  What else should be available as a flavor to download, outside of os/compiler + static/dynamic?

**Comment by Neverlord** [comment]
> The ABI issue is fixed, and I have a general solution in place for the package test.

Great! 👍 

> They recommend that we cut down the number of tests to the minimum needed to verify that the package has all the right bits (headers and libs).

I think running `libcaf_io/test/basp.cpp` should be enough, as it touches most components in CAF and depends on the core and I/O libs (without actually doing I/O):

```
./build/bin/caf-test -s io_basp
```

The repository for the conan recipe is https://github.com/actor-framework/conan.

> What else should be available as a flavor to download, outside of os/compiler + static/dynamic?

Good question. Maybe logging.

**Comment by sourcedelica** [comment]
It's ready for you to take a look.

**Comment by sourcedelica** [comment]
If you pulled between my last comment and this one please pull again.  I squashed the commits.

I'm going to work off a branch in the future.

**Comment by sourcedelica** [comment]
I built CAF with VS 2015 today and it built fine.  Some of the tests crashed.   I need to switch the recipe to use `cmake` instead of `configure` to get it working across platforms.

**Comment by Neverlord** [comment]
@sourcedelica I have to admit I lost sight of this. Can I close the issue or does it still require some action?

**Comment by sourcedelica** [comment]
I had a chance to read through the instructions finally :) .  In order to get the package accepted there is some CI setup to do and a little polishing.   I can take care of that before submission, probably next weekend.

**Comment by Neverlord** [comment]
Thank you for contributing so much time. I will have a look at the guide and register the CAF organization in the next couple of days.
