### ISSUE TITLE
Adopt C++17 API for caf::variant

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#525]
We should remodel `caf::variant` according to the API of C++17 `variant`. This will allow us to drop our custom implementation eventually.

**Comment by mavam** [comment]
Do you want [Broker's implementation](https://github.com/bro/broker/blob/topic/matthias/actor-system/broker/detail/variant.hh)? I made it C++17 compliant.

**Comment by Neverlord** [comment]
Sure. :)

**Comment by mavam** [comment]
Feel free to copy & paste then. [VAST's implementation](https://github.com/vast-io/vast/blob/master/libvast/vast/variant.hpp) is also C++17 compliant, FWIW, but requires C++14 to support variadic lambdas and perfect forwarding of return types via `decltype(auto)`. Moreover, I've came to appreciate what I call the *Variant* concept:

```cpp
// -- variant concept -------------------------------------------------------
//
// The *variant* concept comes in handy for types which contain a (recursive)
// variant but would like to be treated with variant interface externally.
// Such types benefit from uniform access of the variant aspect, namely
// visitation and selective type checking/extraction. To model the *variant*
// concept, a type `V` must provide the following free function to be found via
// ADL:
//
//    variant<Ts...>& expose(V& x)
//
// This function enables the following functions:
//
//    1) `decltype(auto) visit(Visitor, Vs&&... vs)`
//    2) `auto get_if<T>(V&& x)`
//    3) `auto get<T>(V&& x)`
//    4) `bool is<T>(V&& x)`
//
// (1)-(3) have the same semantics as the corresponding function from C++17's
// std::variant. (4) is an idiomatic shortcut for `get_if<T>(v) == nullptr`.
// Note that `variant<Ts...>` trivially models the variant concept.
```

Could be worth adopting if you have use cases for that. In VAST, I have plenty. Many types are implemented in terms of variants and type dispatching happens with visitors. At the same time, these types also have some common state (e.g., like a `.name()` member function). 

This form of type erase makes more sense than virtual polymorphism, because variants can be readily shipped in messages.

**Comment by josephnoir** [comment]
Since CAF is currently limited to the C++11 feature set, we'll have to wait a while. Maybe we could consider a move to C++14 for CAF 0.16?

**Comment by grahamreeds** [comment]
I would prefer to get UDP plus bugfixes in before you consider dropping
C++11.

GR

**Comment by Neverlord** [comment]
Don't worry. We won't drop C++11 support any time soon.

**Comment by mavam** [comment]
Given the C++11 requirement, going with Broker's variant implementation seems to be the natural fit. Once we're on C++14, we can add the missing pieces.

**Comment by Neverlord** [comment]
@mavam Adding a few additions to make CAF's variant more C++17 compatible was easier than ripping out Broker's implementation. I also have a feeling that Broker's implementation might impact compile time more than CAF's. But I don't have the cycles to do a proper benchmarking.
