### ISSUE TITLE
[Question] Game Development, Actor framework and Entity-Component.

### ISSUE THREAD

**Issue by russkiemafia** [actor-framework/actor-framework#539]
Hey there, I would like to ask few things that concern me about game development, but unsure if this fits here, in issue catalogue as I don't think there is any other way to contact the developers regarding it.

I would like to ask if it is possible to use actor-framework for game development specifically for server-side computation where physics are applied, network messages are being received and sent each microsecond to many different players in the game without having any performance loss overall. Is there any difference regarding ECS and Actors? From my perspective Actor framework does what ECS can't and in more elegant and performant way.

Regards.

**Comment by mavam** [comment]
> Hey there, I would like to ask few things that concern me about game development, but unsure if this fits here

Since this is not a specific question about the code, our mailing list would be the appropriate medium here: https://groups.google.com/d/forum/actor-framework

> I would like to ask if it is possible to use actor-framework for game development specifically for server-side computation where physics are applied, network messages are being received and sent each microsecond to many different players in the game without having any performance loss overall.

In general: yes, the actor model (and CAF in particular) is a good fit for your use case. I don't know whether it makes sense to compare the actor model and ECS, since the latter is more of a high-level design pattern as opposed to a concrete structure for a program. The actor model specifies the communication modalities concretely: an actor can do exactly three things: (i) spawn new actors, (ii) send messages to other actors, and (iii) designate the behavior of how to handle the next message.

CAF gives you a high-performance message-passing runtime that takes care of concurrency and distribution. Our work-stealing scheduler operates in the microsecond regime, which seems to work for your requirements.

I'm closing the issue here, feel free to keep the discussion going on the mailing list.
