### ISSUE TITLE
Support integration of unit test data

### ISSUE THREAD

**Issue by mavam** [actor-framework/actor-framework#555]
Per discussion with @rsmmr, it would be helpful to have mechanism in the unit testing framework to retrieve a path to a directory with auxiliary data.

I can think of two approaches. First, we could simply use the existing function `engine::path()` that returns the path of the unit test executable as in `argv[0]`. The problem is that this depends on the invocation and is not very robust.

Alternatively, we could add two new functions to set and retrieve a custom "data" path:

```cpp
class engine {
public:
  static void engine::data_dir(std::string dir);
  static const std::string& engine::data_dir();
};
```

By default, `data_dir()` would return `.`, i.e., the current directory. In a concrete test, one could then write:

```cpp
TEST(foo) {
  auto& dir = engine::data_dir();
  std::ifstream ifs{dir + "/data.txt"};
  ...
}
```

Thoughts?

**Comment by mavam** [comment]
In our last discussion we've agreed that @Neverlord takes care of the issue when integrating the unit tests.

**Comment by Neverlord** [comment]
I don't take care of the issue. I only make sure the unit tests run if the files aren't in the probed paths.

**Comment by Neverlord** [comment]
After giving this more thought, I think we should move away from bundling files. The `caf-test` binary should remain location independent.

Why not implement a Qt-inspired resource system? That would mean we let CMake build a resource file (essentially a `.cpp` file with the file content as static buffer) that gets baked into the binary. Then we can get that buffer from the test framework, e.g. via `engine::resource("data.txt")`.

The only tricky part is getting OpenSSL to work with such "virtual files". It seems like there's no counterpart to `SSL_CTX_use_certificate_chain_file` that operates on buffers.

**Comment by josephnoir** [comment]
Would something like a socketpair work? 🤔

**Comment by Neverlord** [comment]
> actually expects a filename to open

Yes it does. And the function called by `SSL_CTX_use_certificate_chain_file` is [buried in a .cpp file](https://github.com/openssl/openssl/blob/b0edda11cbfe91e8b99b09909a80a810d0143891/ssl/ssl_rsa.c#L589), so we can't even skip the file I/O part and call the right functions directly.

I was thinking whether named pipes could somehow offer a way out. It's still ugly, though, because it involves syscalls and the pipes are visible on the file system (e.g. `/tmp/caf-[PID]/data.txt`). In theory, OpenSSL allows hooking into the file management via custom BIOs, but that seems quite heavyweight (and brittle). Duplicating what `SSL_CTX_use_certificate_chain_file` does internally doesn't strike me as a good idea, either. Having a test-mode in the OpenSSL module that triggers different code paths also defeats the point of a test suite.

This OpenSSL module really turned out to be a major pain. Maybe we should look into alternatives to OpenSSL that offer a better API.

**Comment by josephnoir** [comment]
Named pipes read like they would work here.

> This OpenSSL module really turned out to be a major pain. Maybe we should look into alternatives to OpenSSL that offer a better API.

What would our requirements be, a replacement library that implements TLS or do we just want to offer transport encryption and authentication in some way?

Alternatives that come to mind are [GnuTLS](https://gnutls.org), [NaCL](http://nacl.cr.yp.to)/[libsodium](https://github.com/jedisct1/libsodium), and  searching online also turned up [NSS](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/NSS/Overview). [BoringSSL](https://boringssl.googlesource.com/boringssl/) carries a warning for third parties to avoid it. Can't say if their APIs are nicer and offer a solution for this particular problem.

**Comment by Neverlord** [comment]
Yet another idea: if we already have the file content baked into the test binary, it's easy to dump the file back to disk on demand. For example via `engine::resource("cert.pem").write("caf-test/cert.pem");`. Afterwards, we can pass `"caf-test/cert.pem"` to the OpenSSL module. It's a bit of a hack, but still a lot less involved than named pipes etc. We need write permission in the local directory, but that's about it.

**Comment by Neverlord** [comment]
In the recent `caf-net`, I eventually settled on having CMake generate absolute paths to the test data. I don't see a use case where we would install or ship the unit test binaries, so pointing back to the source tree is fine. These files (keys and certificates) also don't get modified by the unit tests, so let's not overthink this.
