### ISSUE TITLE
add delayed_request feature

### ISSUE THREAD

**Issue by skorokhod** [actor-framework/actor-framework#584]
It's quite often use case when actor should repeat some requests to a server.  Zero timeout (or optional?) should give an ordinary request

like in this scenario:
```
void send_request_to_server(bool first_try, std::chrono::seconds retry_timeout)
{
    delayed_request(target, first_try ?  std::chrono::seconds(0) : retry_timeout, msg).then
    (
     [&](good_response& r)
     {
     }
    ,[&](eror& r)
     {
        send_request_to_server(false, retry_timeout);
     }
    );
}
```

**Comment by josephnoir** [comment]
Looking at `delayed_send`, a `delayed_request` would accept an additional timeout after which the request is issued, i.e., a delay on the sender side in addition to the timeout after which the request fails.

So, using pseudocode, something like this:
```
void delayed_send(destination, delay, message);
void delayed_request(destination, delay, timeout, message);
```

Using an actor, your code would look something like the following, right?

```
self->send(self, try_atom::value);
self->become(
  [=](try_atom) {
    self->request(dest, failure_timeout, get_atom::value).then(
      [&](result&) {
        // handle result
      },
      [&](error& err) {
        self->delayed_send(self, retry_timeout, try_atom::value);
      }
    );
  }
);
```

But if you don't have an actor to send the delayed message to, you need a way to delay the request. At the same time you want to be able to handle the error before reissuing the request (otherwise you could choose your failure timeout accordingly)?

```
void send_request_to_server(bool first_try, seconds retry_timeout) {
  delayed_request(dest, first_try ? seconds(0) : retry_to, failure_to, msg).then(
    [&](result& r) {
      // handle result
    },
    [&](error& r) {
      // received after failure_to
      send_request_to_server(false, retry_timeout); // executed after retry_to
    }
  );
}
```

In this case, you would send the request immediately and then again in an interval of `retry_to + failure_to` until you receive a result.

Does this summarize the problem & proposal?

**Comment by skorokhod** [comment]
Yes, you're right!

**Comment by Neverlord** [comment]
I think rather than adding a narrow feature like `delayed_request`, we should rather implement a more generic `run_delayed` and `run_scheduled` function pair:

```c++
void send_request_to_server(std::chrono::seconds retry_timeout)
{
    request(target, caf::infinite, msg).then
    (
     [&](good_response& r)
     {
     }
    ,[&](eror& r)
     {
      run_delayed(retry_timeout, [=] { send_request_to_server(false, retry_timeout); });
     }
    );
}
```

The idea is to give actors a simple way to run some piece of code in the future. This makes is trivial to implement a delayed request and has many more applications besides that.

**Comment by Neverlord** [comment]
After collecting some experience with the new `run_delayed` and `run_scheduled` utilities, I think they are indeed the way to go here.
