### ISSUE TITLE
CAF base thread schedule

### ISSUE THREAD

**Issue by tlchun** [actor-framework/actor-framework#587]
1.CAF base thread schedule,whether can be based on coroutines scheduling.
2.Coroutines scheduling model like golang.

**Comment by josephnoir** [comment]
Hi, @tlchun.  I am unsure of your intentions. Is there a question here, a suggestion or ... am I missing something?

**Comment by Neverlord** [comment]
We did have coroutine-based actors in the past. Originally based on `getcontext`/`swapcontext` and later based on Boost coroutines. The former is broken and the latter had a terribly unstable API that broke CAF every couple of months. I don't know if the situation has improved since then. However, we ultimately dropped support not only because of API issues. Coroutine actors are slower than event-based actors due to the context switching and also require a dedicated heap.

**Comment by tlchun** [comment]
Base libgo coroutine or Tboox coroutine,Tboox的context switching very high,url:http://tboox.org/cn/2016/10/28/benchbox-coroutine/.Really looking forward to test.
