### ISSUE TITLE
Unit Tests for UDP crashes on Windows

### ISSUE THREAD

**Issue by Hamdor** [actor-framework/actor-framework#645]
The crash happens in test suite `io_dynamic_remote_actor_udp`. The test there is `identity_semantics_udp`.  This is reproducible on Windows 7 and 10 with VS 2017.

**Comment by josephnoir** [comment]
I found the crash in the `ip_endpoint` unit test. It doesn't load the middleman and thus `WSAStartup` is never called. I'll push a fix when I've found the other issues.

As you mentioned, there are several issues in the `io_dynamic_remote_actor_udp` test and I havn't found them all. In the first few cases, adding `server_side.await_all_actors_done();` to the end of the test cases seems to help. I say seems because sometime the cases still crash and I'm not sure why. Maybe I'm not cleaning things up correctly? Will investigate a bit more. Here is the error message, thrown in `xhash`. 
```
Unhandled exception thrown: read access violation.
**this** was 0x300. occurred
```


The last test cases, `multiple_endpoints_udp`, simply stops at different points. Sometimes one actor connects, sometimes two or three ... still a bit stumped as to why this happens.
