### ISSUE TITLE
./hello_world: error while loading shared libraries: libcaf_core.so.0.15.7: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by marcoippolito** [actor-framework/actor-framework#689]
Hi,
in my Ubuntu 16.04 Server Edition I compiled actor-framework using autotools:

`cd actor-framework-master
./ configure
make -j4
make check
sudo make install
`
But.. : 
```
$ g++ -std=c++17 hello_world.cpp -lcaf_core -lcaf_io -ohello_world -L /home/marco/actor-framework-master/lib/libcaf_io.so.0.15.7
$ export LD_LIBRARY_PATH=/home/marco/actor-framework-master/lib/libcaf_io.so.0.15.7
$ ./hello_world
./hello_world: error while loading shared libraries: libcaf_core.so.0.15.7: cannot open shared object file: No such file or directory
```
What am I missing?
Marco

**Comment by josephnoir** [comment]
Hi Marco,

this does not sound like it is related to CAF, but a general C++/Linux question. Here are some pointers:

* Normally CAF builds the examples as well and the binaries are located in `build/bin`.
* If you installed CAF, you don't need to link the libraries located in you build folder but can use the installed ones instead, in `/usr/local/lib` per default. For example: `g++ -std=c++17 hello_world.cpp -lcaf_core -lcaf_io -ohello_world -L/usr/local/lib`. In the same way you should export the `LD_LIBRARY_PATH` to include that folder.
* Since you did not have to specify the include path or the `libcaf_core` library I'd guess that installed ones were used.
* The way you build and linked the examples, you only exported the path to `libcaf_io` and not `libcaf_core`. If you want to use the build folder, set the `LD_LIBRARY_PATH` to `/home/marco/actor-framework-master/lib/` or link both libraries (`libcaf_core` and `libcaf_io`) with their complete path.

Raphael

**Comment by marcoippolito** [comment]
Hi Raphael,
I was just writing that I solved in this way:

 `marco@PC:~/actor-framework-master/examples$ g++ -std=c++17 hello_world.cpp -lcaf_core -lcaf_io -ohello_world -L /usr/local/lib
marco@PC:~/actor-framework-master/examples$ ./hello_world
`

Anyway... thank you very much. 
Marco

**Comment by mavam** [comment]
> What am I missing?

Initially, you did this:

> `$ export LD_LIBRARY_PATH=/home/marco/actor-framework-master/lib/libcaf_io.so.0.15.7`

`LD_LIBRARY_PATH` takes a path to a *directory* containing shared libraries, not a path to a library itself. The same applies to `-L/path/to/dir` link option.

**Comment by josephnoir** [comment]
On macOS you can pass libraries to the `-L` flag as well, I'd guess the same is true for Linux. At least that worked in my brief test.
