### ISSUE TITLE
TCP Test SegFaults

### ISSUE THREAD

**Issue by cooperpellaton** [actor-framework/actor-framework#729]
Running the TCP_Test results in a segfault. Additionally when using this configuration for compilation: `./configure.py --mode="release" --compiler="g++-5" --cflags="-Wno-unused-variable -g"` no debug files are created and GDB cannot be used to trace back the segfualt despite that fact that `-g` is enabled at compile time.

Running on Ubuntu 16.04 with CAF release 17.05.

**Comment by josephnoir** [comment]
Hello, thanks for reporting the issue! I have a few questions to help debug this: 
* As there is no `configure.py` in CAF, what does the script do or where does it come from? The configure script in the repository will ignore `CFLAGS` but pick up exported `CXXFLAGS` which might explain why the `-g` flag had no effect? (You have to be careful here as exporting `CXXFLAGS` will overwrite most of the flags CAF usually [adds per default](https://github.com/actor-framework/actor-framework/blob/master/CMakeLists.txt#L339).) Could you provide the `Build Summary` printed by Cmake?
* Regarding the failing tests, which test cases fail? You can execute a specific test suit in with the `caf-test` executable with the `-s` flag. Since this matches substring `-s tcp` should execute all tcp-related test suits.

**Comment by cooperpellaton** [comment]
My apologies, I meant to submit this to Seastar, not CAF as I am currently working with both and got mixed up after a long day. The issue can be marked as closed.
