### ISSUE TITLE
0.16.0 incompatible with Qt (slots keyword)

### ISSUE THREAD

**Issue by dndanik** [actor-framework/actor-framework#771]
Qt defines `slots` keyword. It makes 0.16.0 headers incompatible with Qt.
Every variable named `slots` gets replaced with nothing.
For example `stream_slots slots;` -> `stream_slots ;`

**Comment by Neverlord** [comment]
That's why macros like this are a bad idea.

**Comment by Neverlord** [comment]
I have to put this into the wontfix category. It's unfortunate, that we still have to deal with macro nonsense like this because of some bad design decisions in C some decades ago.

One has to be careful with his `includes`. For example, including `windows.h` the wrong way will break CAF (and many other C++ libraries) by defining `min` and `max`. The fix here is to include CAF headers always before including Qt headers. A workaround in CAF would touch too many files and we're not going to compromise on terminology.

**Comment by firegurafiku** [comment]
@dndanik 

Just for the sake of the discussion completeness, CAF is *not* incompatible with Qt. Just use [`no_keywords`][1] configuration option which effectively disables the `slots` macro (and some others); add the following into your `*.pro` file:

    CONFIG += no_keywords

and use `Q_SLOTS` instead of `slots` (and `Q_SIGNALS`, `Q_EMIT`, etc). I personally think that should be the preferred way to code regardless the `no_keywords` is used or not.

[1]: http://doc.qt.io/qt-5/signalsandslots.html#using-qt-with-3rd-party-signals-and-slots
