### ISSUE TITLE
0.16.0 message priorities feature seems broken.

### ISSUE THREAD

**Issue by ke9** [actor-framework/actor-framework#776]
While upgrading from 0.15.7, found out in the code that caf::priority_aware seems deprecated, but the documentation still mentions message priorities (normal & high).

Messages do not respect priority anymore, and even when sending a high priority messages before normal priority ones, they will not be handled in the proper order by actors. Normal priority will be handled before high priority message even if these have been sent beforehand.

Is there a new/better way to send urgent messages to actors ?

**Comment by Neverlord** [comment]
Sorry for the lackluster documentation.

The `priority_aware` flag is deprecated, because *all* actors respect message priorities as of 0.16. The mailbox internally always uses multiple queues now. However, the queue holding regular messages currently gets checked first (see #684), why it may appear that regular messages have precedence. This is not intentional and will get fixed.
