### ISSUE TITLE
Serialize outgoing messages in proxy instances

### ISSUE THREAD

**Issue by Neverlord** [actor-framework/actor-framework#820]
Currently, the BASP broker serializes all outgoing messages. This slows the multiplexer thread (also see #819), causing CAF to waste cycles in this thread it should rather spend doing I/O. By moving the serialization into the proxies and scheduling them as ordinary actors, we can offload a significant amount of work.

**Comment by Neverlord** [comment]
I've implemented this in `topic/basp-proxy`. However, the performance plummets hard. Allocating buffers in the proxy and then ship them to the BASP broker is more expensive then doing the serialization directly.

That could be solvable with an efficient  buffer recycling policy. However, just offloading the deserialization gives enough of a boost: https://github.com/actor-framework/actor-framework/pull/821.

Intelligent buffer management is something we need to put into the redesigned network stack, but this story is a noshow for now.

**Comment by josephnoir** [comment]
Just to clarify this for future discussions. Serializing the data outside the BASP broker adds an allocation for the buffer to serialize into and an additional copy operation since we still have to copy the serialized data into the send buffer for the multiplexer. Correct? (I didn't look a the branch.)

I can see how this might be a problem overall. But in a scenario where the multiplexer is actually the bottle neck I'd have expected the copy to be more efficient than the serialization. Did you measure this with multiple proxies and does it pay off at some point?

**Comment by Neverlord** [comment]
Copying is comparatively cheap. The performance gains in https://github.com/actor-framework/actor-framework/pull/821 clearly show that offloading can be efficient. However, we do the offloading with workers that own and re-use their buffers. We read from socket, copy into the already allocated worker buffer and throw the worker into a job queue. There's no allocation involved other than constructing the `caf::message` at the end.

For the clean-slate `caf_net` design, I think we ultimately want to replace the BASP broker with an efficient buffer-queue with an intelligent allocation strategy. Then, a proxy would retrieve a buffer from the socket manager and fill it (as opposed to always allocate new storage).
