### ISSUE TITLE
Broker server doesn't shut down connections properly

### ISSUE THREAD

**Issue by CrazyIvan32** [actor-framework/actor-framework#857]
When shutting down broker that acts as a server the listening socket doesn't seem to be closed properly. If I try to start the same program immediately after it finished it could not bind to the same port and netstat shows it's still in use (eventually OS closes it). It happens if there were some connections to the server during server operation. 

It can be easily reproduced with simple_http_broker example:
```
./simple_http_broker -p 9999
*** error in config file [line 11 col 21]: unexpected_character
*** listening on port 9999
*** to quit the program, simply press <enter>
Finished 0 requests per second.
Finished 0 requests per second.
Finished 0 requests per second.
Finished 0 requests per second.
Finished 0 requests per second.
Finished 0 requests per second.
Finished 0 requests per second.
Finished 0 requests per second.
Finished 1 requests per second.
Finished 0 requests per second.

```

And then the following happens:
```
./simple_http_broker -p 9999
*** error in config file [line 11 col 21]: unexpected_character
*** cannot spawn server: system_error(cannot_open_port, ("tcp socket creation failed", 9999, ""))
```

**Comment by josephnoir** [comment]
I don't think this is a bug. As far as I can tell we close the socket correctly. I want to say the system still has a time out before it allows reusing the port to avoid receiving old packets on new sockets.

One way to avoid this is setting `SO_REUSEADDR`. If you spawn a broker directly instead of using the `spawn_server` convenience function you can enable this option via the `reuse_addr` argument of [`add_tcp_doorman`](https://github.com/actor-framework/actor-framework/blob/master/libcaf_io/caf/io/abstract_broker.hpp#L207).

**Comment by CrazyIvan32** [comment]
Yes, this seems to be the case
