### ISSUE TITLE
Config file could be silently ignored, application can run with unintended parameters

### ISSUE THREAD

**Issue by andrismednis** [actor-framework/actor-framework#947]
Attachment [demo_files.tar.gz](https://github.com/actor-framework/actor-framework/files/3769372/demo_files.tar.gz) contains a minimal CAF application which uses CAF built-in feature for parsing and getting a user-defined parameter from the config file.

It works as expected when the config file exists and is accessible via absolute pathname or a simple relative pathname:
```
$ ./myapp --config-file=/home/user/my_app.ini
DebugLevel = 4
$ ./myapp --config-file=my_app.ini
DebugLevel = 4
$ ./myapp --config-file=./my_app.ini
DebugLevel = 4
$ ./myapp --config-file=../user/my_app.ini
DebugLevel = 4
```
However, it silently ignores a non-existing config file or one with '~':
```
$ ./myapp --config-file=zzzzzz
DebugLevel = 65535
$ ./myapp --config-file=~/my_app.ini
DebugLevel = 65535
```
I expected that the application stops with error message about a problem with config file.

**Comment by Neverlord** [comment]
Thank you for reporting this! It fell a bit on the wayside due to higher priorities.

> I expected that the application stops with error message about a problem with config file.

This is what you should expect. The reason CAF ignores non-existing files silently is that we otherwise would get an error whenever the (optional) default file does not exist. However, it's a different story if the user explicitly sets a config file via the CLI. Shouldn't be hard to fix, though.

**Comment by andrismednis** [comment]
Great! Thanks!
