### ISSUE TITLE
Online doc is broken since 0.17.0

### ISSUE THREAD

**Issue by lowsfer** [actor-framework/actor-framework#956]
How to verify:
Go to https://actor-framework.readthedocs.io/en/0.17.0/Actors.html
search "Spawning an actor for each implementation is illustrated below."

There is no sample code shown below. If you switch to 0.16 or earlier, the sample code is there. I see there are many similar missing code examples and UML diagrams.

**Comment by Neverlord** [comment]
Thanks for reporting! Also, I noticed that read-the-docs still has 0.17.1 as the most recent version (should be 0.17.2).

**Comment by Neverlord** [comment]
It seems like recent `pandoc` versions broke pretty much everything. The Python filter (`pandoc-filter.py`) no longer sees any raw block and pandoc silently drops everything it does not recognize. I tried fixing it by giving pandoc special versions for `\cppexample` etc, but then it brakes because Pandoc refuses `\cppexample{hello_world}` (it claims `_` is illegal at this position). Obviously, `\cppexample{hello\_world}` breaks the actual LaTeX build.

Looking the `pandoc` repository, there are already some 470 open issues. I don't think we can count on a timely fix. Also, even if there would be fix right away, then we would have to build most-recent `pandoc` manually instead of using packaged versions.

Getting the initial setup to work in the first place was already a lot of work with some ugly workarounds. Seems like `pandoc` just isn't the right tool. Since our online docs are crucial, we need to find a new (reliable!) setup. Our `.tex` sources are very simple and uniform, so maybe just parsing them manually in Python is the best option. The pandoc filter already translates some constructs by hand anyway. Or we use our parser framework for the job.

**Comment by lowsfer** [comment]
Maybe just use an older version of `pandoc` as a temporary solution, if no new feature is used?

**Comment by Neverlord** [comment]
That would work in the very short term, but maintaining specific, non-standard versions of tools in our CI containers breaks sooner rather than later. And silent breaks like this one are the worst ones to have.

I couldn't find a tool other than Pandoc that could do the job. So I ended up writing a new tool (`caf-generate-rst`) that parses our `.tex` sources and generates a decent `.rst` version. TeX is a Turing complete language, so I didn't bother writing an actual TeX parser. The tool understands the narrow subset we're using in our manual and that's all we need at the moment.

I've already updated the `latest` version in read-the-docs: https://actor-framework.readthedocs.io/en/latest/Actors.html#common-actor-base-types. Pictures, tables, and source code examples are back. There are still tons of broken references, so we'll still have to fix that.

I don't have strong feelings which markup language we should use for our manual. However, I did find the auto-generated `.pdf` version from RTD very lackluster compared to our TeX-generated one. So unless there are some magic tricks we could do to get vector graphics, etc. in the offline version, reStructuredText is not an option. I'm all ears for suggestions as long as we can get the same level of quality for the offline version.

The tool is currently lives in `issue/956`, but I expect to merge it to `master` today (unless our CI panics about some changes).

**Comment by Neverlord** [comment]
Oh, and stuff like `Class lstinline^scheduled_actor^` as section names is already fixed in the branch. That gets sorted out automatically after merging the branch.

**Comment by Neverlord** [comment]
@lowsfer thanks again for reporting! The `latest` tag has a mostly fixed version now: https://actor-framework.readthedocs.io/en/latest/Actors.html. References are not working at the moment and the list under `Class-based Actors` is broken. I'll see if there's a simple fix and otherwise I'll open followup issues.
