### ISSUE TITLE
Allow CAF to optionally produce log files for unit tests

### ISSUE THREAD

**Issue by dominiklohmann** [actor-framework/actor-framework#959]
Since e35d727 CAF no longer produces log files for unit tests when using the `test_coordinator_fixture`, with no easy way to get the old behavior back afaict.

I would really like for this to be configurable. Maintaining a custom fixture is way more effort than making this configurable in CAF.

**Comment by Neverlord** [comment]
I ran into the same issue while working on PR #954. The PR already contains a commit that will allow you to enable log output again via config file. That's at least a temporary workaround. Ideally, CAF unit tests should not access the disk at all. Fixing that properly is a story for another day, since it requires extending the unit test framework.

I'll leave this story open until we have a better way of enabling log output.

**Comment by Neverlord** [comment]
Obsolete. The new log framework merges log output into the regular test output.
