### ISSUE TITLE
Nuget

### ISSUE THREAD

**Issue by grahamreeds** [actor-framework/actor-framework#962]
Any chance of getting CAF in to Nuget? Someone put an older version in there a while back but not recently.

**Comment by Neverlord** [comment]
By "getting CAF in to Nuget", I suppose you mean a package maintained by the core developers directly.

Depends. So far, we only support HomeBrew directly, because we can automate release updates via `brew bump-formula-pr`. As long as Nuget has something that we can setup once and then automate: sure. Could you provide initial scaffolding and a quick how-to-automate guide?

**Comment by grahamreeds** [comment]
I am more of a consumer than a producer but I can give it a try.

A cursory Google search seems to suggest that people delegate the task to
MyGet.  Personally I would prefer to keep it within GitHub.

How do you feel about that?

**Comment by Neverlord** [comment]
> How do you feel about that?

I got to admit I'm not sure what you mean by "MyGet vs GitHub". Anything we can automate via script works for us. We do all my releases with a shell script that automatically updates our HomeBrew package. It would be ideal if we could just add a couple extra lines to [that script](https://github.com/actor-framework/actor-framework/blob/master/scripts/make_release.bash). If we need to run something on Windows (e.g. because we need to upload compiled versions): we have our own Jenkins that could to that via Groovy scripts.

**Comment by grahamreeds** [comment]
I was probably a bit hasty with the my original terse reply.

MyGet is a third party site that bills itself as Nuget as a service. The documentation seems to think that you will be publishing a .NET project and nothing is mentioned about native projects.  I will look at this 

Another alternative is a Powershell command 'Write-NuGetPackage'.  This is what the company I work for use.  However we have a local Nuget repository and our product is Windows based so running a powershell commands during our build phase is no biggy.

Do you run that script locally or is it run remotely?

**Comment by grahamreeds** [comment]
I notice that CAF is already in vcpkg, currently for 17.2.  vcpkg is like NuGet but for native c++ code.  The source is downloaded and then compiled 

Reading about vcpkg this is probably more a natural fit than NuGet.  The big thing for nuget is the ease of use - no messing about adding libs to a project and setting up the references as it is all done for you - add the header to the source and away you go.

**Comment by sourcedelica** [comment]
CAF is also in Conan Center: https://conan.io/center/caf/0.17.3/?user=bincrafters&channel=stable.

[Conan](https://conan.io/) is a package manager for C/C++.

**Comment by Neverlord** [comment]
> Reading about vcpkg this is probably more a natural fit than NuGet.

Closing this then. 🙂
